const fs=require('fs');let q=fs.readFileSync('QRPayNearby.tsx','utf8');
// amount input + QR + Send KAS / Create IOU into BLE RECEIVE card
const old="<Text style={{ color: '#666', fontSize: rs(10), marginTop: rs(12), textAlign: 'center' }}>{address}</Text>\n            </View>";
const nw="<View style={{ backgroundColor: '#FFF', padding: rs(12), borderRadius: rs(10), marginTop: rs(16) }}>\n                <QRCode value={qrPayload} size={rs(180)} />\n              </View>\n              <Text style={{ color: '#87CEEB', fontSize: rs(10), marginTop: rs(8), textAlign: 'center' }}>Scan to connect + get address{parseFloat(requestAmount) > 0 ? ' + ' + requestAmount + ' KAS request' : ''}</Text>\n              <TextInput value={requestAmount} onChangeText={setRequestAmount} placeholder=\"Request amount (KAS) \u2014 optional\" placeholderTextColor=\"#666\" keyboardType=\"decimal-pad\" style={{ width: '100%', backgroundColor: '#0D0D1A', color: '#FFF', borderRadius: rs(10), padding: rs(10), marginTop: rs(12), borderWidth: 1, borderColor: '#333', textAlign: 'center' }} />\n              <Text style={{ color: '#555', fontSize: rs(9), marginTop: rs(10), textAlign: 'center' }}>{address}</Text>\n            </View>\n            <View style={{ flexDirection: 'row', gap: rs(8), marginTop: rs(14), width: '100%' }}>\n              <TouchableOpacity style={{ flex: 1, backgroundColor: '#F59E0B', borderRadius: rs(12), padding: rs(14), alignItems: 'center' }} onPress={() => { stopReceiving(); setMode('send_proposal'); }}>\n                <Text style={{ color: '#000', fontWeight: '700', fontSize: rs(14) }}>\uD83D\uDCB8 Send KAS</Text>\n              </TouchableOpacity>\n              <TouchableOpacity style={{ flex: 1, backgroundColor: '#1A1A2E', borderRadius: rs(12), padding: rs(14), alignItems: 'center', borderWidth: 1, borderColor: '#D4AF37' }} onPress={() => { stopReceiving(); setShowIOUSheet(true); }}>\n                <Text style={{ color: '#D4AF37', fontWeight: '700', fontSize: rs(14) }}>\uD83D\uDCD2 Create IOU</Text>\n              </TouchableOpacity>\n            </View>";
if(!q.includes(old)){console.log('ANCHOR FAIL');process.exit(1);}
q=q.replace(old,nw);
// requestAmount state (add if missing)
if(!q.includes("const [requestAmount")) q=q.replace("const [showIOUSheet, setShowIOUSheet] = useState(false);","const [showIOUSheet, setShowIOUSheet] = useState(false);\n  const [requestAmount, setRequestAmount] = useState('');");
fs.writeFileSync('QRPayNearby.tsx',q);console.log('done');
