// build_scene_engine.cjs
// Converts scene_engine.html into scene_engine_html.ts (a TS module exporting
// the engine as a string). Keeping the HTML as the single source of truth means
// the engine stays testable in a plain browser: open scene_engine.html directly.
//
// Run after ANY edit to scene_engine.html:
//   node .\build_scene_engine.cjs

const fs = require('fs');
const SRC = 'scene_engine.html';
const OUT = 'scene_engine_html.ts';

if (!fs.existsSync(SRC)) { console.error('ABORT: ' + SRC + ' not found'); process.exit(1); }
let html = fs.readFileSync(SRC, 'utf8');

// The engine is written without backticks or ${ so it embeds cleanly, but guard
// anyway - a stray one would silently corrupt the template literal.
const bad = [];
if (html.indexOf('`') >= 0) bad.push('backtick');
if (html.indexOf('${') >= 0) bad.push('${');
if (bad.length) {
  console.error('ABORT: engine contains ' + bad.join(' and ') + ' - escape or remove before building');
  process.exit(1);
}

const banner = [
  '// AUTO-GENERATED by build_scene_engine.cjs - DO NOT EDIT BY HAND.',
  '// Source of truth: scene_engine.html (open it in a browser to test).',
  '// Regenerate with: node .\\\\build_scene_engine.cjs',
  '',
  '/* eslint-disable */',
  'export const SCENE_ENGINE_HTML: string = `',
].join('\n');

fs.writeFileSync(OUT, banner + html.replace(/\\/g, '\\\\') + '`;\n');
console.log('OK ' + OUT + ' (' + Math.round(html.length / 1024) + ' KB engine)');
