const fs=require('fs');let q=fs.readFileSync('QRPayNearby.tsx','utf8');
// Shop Here button — add next to Security Verify
q=q.replace("<TouchableOpacity style={{ marginTop: rs(8), backgroundColor: '#1A1A2E', borderRadius: rs(12), padding: rs(14), alignItems: 'center', borderWidth: 1, borderColor: '#e74c3c' }} onPress={() => setMode('verify')}>","<TouchableOpacity style={{ marginTop: rs(8), backgroundColor: '#1A1A2E', borderRadius: rs(12), padding: rs(14), alignItems: 'center', borderWidth: 1, borderColor: '#49d6aa' }} onPress={() => { setCart([]); setMode('shop'); }}>\n                <Text style={{ color: '#49d6aa', fontSize: rs(13), fontWeight: '600' }}>Shop Here (scan items)</Text>\n              </TouchableOpacity>\n              <TouchableOpacity style={{ marginTop: rs(8), backgroundColor: '#1A1A2E', borderRadius: rs(12), padding: rs(14), alignItems: 'center', borderWidth: 1, borderColor: '#e74c3c' }} onPress={() => setMode('verify')}>");
// Receipt QR block in BLE RECEIVE — show after receiptItems set + payment. Add inside the BLE receive card after the amount TextInput.
const amtInput='<TextInput value={requestAmount} onChangeText={setRequestAmount} placeholder="Request amount (KAS)"';
const idx=q.indexOf(amtInput);
if(idx<0){console.log("AMT ANCHOR FAIL");process.exit(1);}
// find end of that TextInput tag
const tagEnd=q.indexOf("/>",idx)+2;
const receiptBlock=`\n              {receiptItems.length > 0 && (\n                <View style={{ marginTop: rs(14), backgroundColor: '#0D2818', borderRadius: rs(12), padding: rs(14), width: '100%', alignItems: 'center', borderWidth: 1, borderColor: '#10B981' }}>\n                  <Text style={{ color: '#10B981', fontWeight: '700', fontSize: rs(13), marginBottom: rs(8) }}>Deterministic Receipt</Text>\n                  <View style={{ backgroundColor: '#FFF', padding: rs(10), borderRadius: rs(8) }}>\n                    <QRCode value={JSON.stringify({ type: 'kv_receipt', items: receiptItems, txId: (globalThis as any).__kvLastTxId || 'PENDING', hash: buildReceiptHash(receiptItems, (globalThis as any).__kvLastTxId || 'PENDING') })} size={rs(150)} />\n                  </View>\n                  <Text style={{ color: '#87CEEB', fontSize: rs(10), marginTop: rs(8), textAlign: 'center' }}>Show at exit — security scans to verify payment</Text>\n                  <TouchableOpacity onPress={() => setReceiptItems([])} style={{ marginTop: rs(8) }}><Text style={{ color: '#666', fontSize: rs(11) }}>Clear receipt</Text></TouchableOpacity>\n                </View>\n              )}`;
q=q.slice(0,tagEnd)+receiptBlock+q.slice(tagEnd);
fs.writeFileSync('QRPayNearby.tsx',q);console.log('done');
