export function validateContentText(text: string): string | null {
  if (!text) return null;
  const lower = text.toLowerCase();
  const blocked = [
    // === ENGLISH: Trafficking & Exploitation ===
    'child trafficking','human trafficking','sex trafficking','labor trafficking',
    'sell children','buy children','exploit children','child exploitation',
    'child pornography','child abuse','minor exploitation',
    'sell child','buy child','exploit child','traffic child','abuse child','groom child','lure child',
    'child sex','child nude','child naked','child porn','child rape','child slave','child bride','child marry','marry child',
    'sex child','nude child','naked child','porn child','rape child','drug child',
    // === ENGLISH: Weapons ===
    'sell weapons','buy weapons','illegal weapons','ghost gun','3d printed gun',
    'sell firearms','buy firearms','unregistered firearm','sell ammunition',
    'sell knives','buy knives','sell switchblade','buy switchblade',
    'sell explosives','buy explosives','pipe bomb','bomb making',
    // === ENGLISH: Drugs ===
    'sell drugs','buy drugs','sell narcotics','buy narcotics',
    'sell cocaine','buy cocaine','sell heroin','buy heroin',
    'sell methamphetamine','buy methamphetamine','sell fentanyl','buy fentanyl',
    'sell mdma','buy mdma','sell lsd','buy lsd',
    'sell opioids','buy opioids','sell pills','buy pills',
    'sell meth','buy meth','sell crack','buy crack','sell weed','buy weed',
    'sell marijuana','buy marijuana','sell ecstasy','buy ecstasy',
    'sell ketamine','buy ketamine','sell pcp','buy pcp',
    'sell xanax','buy xanax','sell adderall','buy adderall',
    'sell morphine','buy morphine','sell tramadol','buy tramadol',
    'sell codeine','buy codeine','sell percocet','buy percocet',
    'sell oxycontin','buy oxycontin','sell vicodin','buy vicodin',
    'date rape drug','roofie','rohypnol','ghb drug',
    'drugs for boy','drugs for girl','drugs for kids','drugs for teen',
    'sell drugs to','give drugs to','drug teen','drug girl','drug boy',
    'drug women','drug female','drug male','drug kids',
    // === ENGLISH: Violence & Murder ===
    'hire hitman','contract killing','murder for hire',
    'sell organs','buy organs','organ trafficking',
    'sell poison','buy poison','sell cyanide','buy cyanide',
    // === ENGLISH: Fraud & Theft ===
    'money laundering','counterfeit currency','counterfeit money',
    'sell stolen','buy stolen','stolen goods','stolen credit card',
    'identity theft','sell identity','buy identity','fake passport','fake id',
    'ransomware','ddos attack','hack for hire','sell exploit',
    // === ENGLISH: Smuggling & Forced Labor ===
    'human smuggling','illegal immigration service',
    'forced labor','slave labor','debt bondage',
    // === ENGLISH: Sexual Exploitation ===
    'revenge porn','non-consensual intimate','sextortion',
    'escort service','prostitution','sell sex','buy sex',
    'rape','molest','sodomy','pedophile','pedophilia','incest',
    'sexual abuse','sexual assault','sex with minor','sex with child',
    'sex with teen','sex with boy','sex with girl','sex with kids',
    'nude boy','nude girl','nude teen','nude child','nude kids',
    'naked boy','naked girl','naked teen','naked child','naked kids',
    'underage sex','underage porn','underage nude',
    'teen porn','teen sex','teen nude',
    'boy sex','girl sex','kids sex',
    'sex slave','sex trade','sex worker','sexual exploitation',
    'anal sex','oral sex','group sex','forced sex','rough sex','unprotected sex',
    'grooming','groom child','groom teen','groom boy','groom girl',
    'lure child','lure teen','lure boy','lure girl',
    'age play','ageplay','lolita','shota',
    'snuff film','snuff video','bestiality','zoophilia',
    'camgirl minor','webcam minor','webcam child','webcam teen',
    // === ENGLISH: Terrorism & Other ===
    'terrorism','terrorist attack','extremist recruitment',
    'suicide instruction','how to kill yourself',
    'animal crush','animal cruelty',
    // === ENGLISH: Gender + Sell/Buy/Exploit/Traffic/Abuse ===
    'sell boy','buy boy','sell girl','buy girl','sell female','buy female',
    'sell male','buy male','sell women','buy women','sell kids','buy kids',
    'sell woman','buy woman','sell man','buy man',
    'exploit boy','exploit girl','exploit kids','exploit women',
    'traffic boy','traffic girl','traffic kids','traffic women',
    'abuse boy','abuse girl','abuse kids','abuse women',
    // === ENGLISH: Age + Gender (10-17) ===
    '10 girl','10yr girl','10 yr girl','10yo girl','10 boy','10yr boy','10 yr boy','10yo boy',
    '10 female','10yr female','10 yr female','10yo female','10 male','10yr male','10 yr male','10yo male',
    '10 year old','10yr year old','10 yr year old','10yo year old','10 child','10yr child','10 yr child','10yo child',
    '11 girl','11yr girl','11 yr girl','11yo girl','11 boy','11yr boy','11 yr boy','11yo boy',
    '11 female','11yr female','11 yr female','11yo female','11 male','11yr male','11 yr male','11yo male',
    '11 year old','11yr year old','11 yr year old','11yo year old','11 child','11yr child','11 yr child','11yo child',
    '12 girl','12yr girl','12 yr girl','12yo girl','12 boy','12yr boy','12 yr boy','12yo boy',
    '12 female','12yr female','12 yr female','12yo female','12 male','12yr male','12 yr male','12yo male',
    '12 year old','12yr year old','12 yr year old','12yo year old','12 child','12yr child','12 yr child','12yo child',
    '13 girl','13yr girl','13 yr girl','13yo girl','13 boy','13yr boy','13 yr boy','13yo boy',
    '13 female','13yr female','13 yr female','13yo female','13 male','13yr male','13 yr male','13yo male',
    '13 year old','13yr year old','13 yr year old','13yo year old','13 child','13yr child','13 yr child','13yo child',
    '14 girl','14yr girl','14 yr girl','14yo girl','14 boy','14yr boy','14 yr boy','14yo boy',
    '14 female','14yr female','14 yr female','14yo female','14 male','14yr male','14 yr male','14yo male',
    '14 year old','14yr year old','14 yr year old','14yo year old','14 child','14yr child','14 yr child','14yo child',
    '15 girl','15yr girl','15 yr girl','15yo girl','15 boy','15yr boy','15 yr boy','15yo boy',
    '15 female','15yr female','15 yr female','15yo female','15 male','15yr male','15 yr male','15yo male',
    '15 year old','15yr year old','15 yr year old','15yo year old','15 child','15yr child','15 yr child','15yo child',
    '16 girl','16yr girl','16 yr girl','16yo girl','16 boy','16yr boy','16 yr boy','16yo boy',
    '16 female','16yr female','16 yr female','16yo female','16 male','16yr male','16 yr male','16yo male',
    '16 year old','16yr year old','16 yr year old','16yo year old','16 child','16yr child','16 yr child','16yo child',
    '17 girl','17yr girl','17 yr girl','17yo girl','17 boy','17yr boy','17 yr boy','17yo boy',
    '17 female','17yr female','17 yr female','17yo female','17 male','17yr male','17 yr male','17yo male',
    '17 year old','17yr year old','17 yr year old','17yo year old','17 child','17yr child','17 yr child','17yo child',
    'teen sex','teen girl sex','teen boy sex','preteen','pre-teen','preteen sex','pre-teen sex',
    'teen female','teen male','minor sex','minor nude','minor naked',
    'underage girl','underage boy','underage female','underage male','young girl sex','young boy sex','young teen',
    // === SPANISH ===
    'trata de personas','vender drogas','comprar drogas','vender armas','comprar armas',
    'trata de ninos','explotacion infantil','pornografia infantil','vender cocaina',
    'comprar cocaina','vender heroina','comprar heroina','lavado de dinero',
    'asesino a sueldo','trafico de organos','trabajo forzado','vender explosivos',
    'comprar explosivos','identidad falsa','pasaporte falso',
    'violacion','abusar sexualmente','abuso sexual',
    'sexo con menor','sexo con nino','sexo con nina','desnudo menor',
    'drogas para ninos','drogar mujer','drogar chica','pedofilia',
    'trata sexual','esclava sexual','acoso sexual menor',
    'vender metanfetamina','comprar metanfetamina','vender crack','comprar crack',
    'vender marihuana','comprar marihuana','vender extasis','comprar extasis',
    'sexo anal','sexo oral','sexo grupal','sexo forzado',
    'sexo adolescente','menor desnuda','menor desnudo','preadolescente',
    'vender ninos','comprar ninos','vender ninas','comprar ninas',
    'vender nino','comprar nino','sexo nino','sexo nina','desnudo nino','desnuda nina',
    '10 anos nina','10 anos nino','10 anos chica','10 anos chico',
    '11 anos nina','11 anos nino','11 anos chica','11 anos chico',
    '12 anos nina','12 anos nino','12 anos chica','12 anos chico',
    '13 anos nina','13 anos nino','13 anos chica','13 anos chico',
    '14 anos nina','14 anos nino','14 anos chica','14 anos chico',
    '15 anos nina','15 anos nino','15 anos chica','15 anos chico',
    '16 anos nina','16 anos nino','16 anos chica','16 anos chico',
    '17 anos nina','17 anos nino','17 anos chica','17 anos chico',
    // === FRENCH ===
    'traite des personnes','vendre des drogues','acheter des drogues','vendre des armes',
    'acheter des armes','exploitation des enfants','pornographie infantile',
    'vendre de la cocaine','acheter de la cocaine',"blanchiment d'argent",
    "tueur a gages","trafic d'organes",'travail force','vendre des explosifs',
    'acheter des explosifs','faux passeport','fausse identite',
    'viol','abus sexuel','sexe avec mineur','pornographie enfantine',
    'nu mineur','droguer fille','droguer femme','pedophilie',
    'esclave sexuel','exploitation sexuelle','vendre crack','acheter crack',
    'vendre marijuana','acheter marijuana','vendre ecstasy','acheter ecstasy',
    'sexe anal','sexe oral','sexe force',
    'sexe ado','mineur nu','mineur nue','preadolescent',
    'vendre fille','acheter fille','vendre garcon','acheter garcon',
    'vendre enfant','acheter enfant','sexe enfant','nu enfant',
    '10 ans fille','10 ans garcon','11 ans fille','11 ans garcon',
    '12 ans fille','12 ans garcon','13 ans fille','13 ans garcon',
    '14 ans fille','14 ans garcon','15 ans fille','15 ans garcon',
    '16 ans fille','16 ans garcon','17 ans fille','17 ans garcon',
    // === GERMAN ===
    'menschenhandel','drogen verkaufen','drogen kaufen','waffen verkaufen',
    'waffen kaufen','kinderpornographie','kinderausbeutung','geldwaesche',
    'auftragsmord','organhandel','zwangsarbeit','terrorismus','sprengstoff',
    'vergewaltigung','sexueller missbrauch','sex mit minderjaehrigen',
    'kinderporno','nackt minderjaehrig','drogen maedchen','paedophilie',
    'sexsklave','sexuelle ausbeutung','crack verkaufen','crack kaufen',
    'analsex','oralsex','gruppensex','erzwungener sex',
    'teenager sex','minderjaehrig nackt','minderjaerige',
    'maedchen verkaufen','jungen verkaufen','kind verkaufen','kind kaufen',
    'sex kind','nackt kind',
    '10 jahre maedchen','10 jahre junge','11 jahre maedchen','11 jahre junge',
    '12 jahre maedchen','12 jahre junge','13 jahre maedchen','13 jahre junge',
    '14 jahre maedchen','14 jahre junge','15 jahre maedchen','15 jahre junge',
    '16 jahre maedchen','16 jahre junge','17 jahre maedchen','17 jahre junge',
    // === PORTUGUESE ===
    'trafico de pessoas','exploracao infantil','lavagem de dinheiro',
    'assassino de aluguel','trafico de orgaos','trabalho forcado',
    'estupro','sexo com menor',
    'nu menor','drogar menina','drogar mulher',
    'escravo sexual','exploracao sexual','vender crack','comprar crack',
    'sexo forcado','menor nua','menor nu','pre-adolescente',
    'menina vender','menino vender','vender crianca','comprar crianca',
    'sexo crianca','nu crianca',
    '10 anos menina','10 anos menino','11 anos menina','11 anos menino',
    '12 anos menina','12 anos menino','13 anos menina','13 anos menino',
    '14 anos menina','14 anos menino','15 anos menina','15 anos menino',
    '16 anos menina','16 anos menino','17 anos menina','17 anos menino',
    // === RUSSIAN (transliterated) ===
    'torgovlya lyudmi','prodat narkotiki','kupit narkotiki','prodat oruzhie',
    'kupit oruzhie','detskaya pornografiya','ekspluataciya detey','terrorizm',
    'otmyvanie deneg','naemnyy ubiyca','torgovlya organami','prinuditelnyy trud',
    'iznasilovanie','seksualnoe nasilie','seks s nesovershennoletnim',
    'detskoe porno','golyy rebenok','pedofiliya','seksualnyy rab',
    'prodat metamfetamin','kupit metamfetamin','prodat marihuanu','kupit marihuanu',
    'analnyy seks','oralnyy seks','gruppovoy seks','prinuditelnyy seks',
    'podrostok seks','golaya nesovershennoletnyaya','nesovershennoletnyaya',
    'prodat devochku','kupit devochku','prodat malchika','kupit malchika',
    'prodat rebenka','kupit rebenka','seks rebenok',
    '10 let devochka','10 let malchik','11 let devochka','11 let malchik',
    '12 let devochka','12 let malchik','13 let devochka','13 let malchik',
    '14 let devochka','14 let malchik','15 let devochka','15 let malchik',
    '16 let devochka','16 let malchik','17 let devochka','17 let malchik',
    // === ARABIC (transliterated) ===
    "itjar bil bashar","bay'a mukhadarat","shira mukhadarat","bay'a aslaha",
    "shira aslaha",'istighlal atfal','irhab','tazyif amwal','qatil majur',
    "itjar a'da",'amal qasri',
    'ightisab','itida jinsi','jins maa qasir','suar atfal',
    'takhdir fatah','bidufiliya','abd jinsi',
    'jins sharji','jins fami','jins murahiq','qasir ari',
    'bay tifl','shira tifl','jins tifl','ari tifl',
    '10 sana bint','10 sana walad','11 sana bint','11 sana walad',
    '12 sana bint','12 sana walad','13 sana bint','13 sana walad',
    '14 sana bint','14 sana walad','15 sana bint','15 sana walad',
    '16 sana bint','16 sana walad','17 sana bint','17 sana walad',
    // === CHINESE (pinyin) ===
    'mai du pin','mai wu qi','fan mai ren kou','er tong se qing',
    'xi qian','gu yong sha shou','qi guan mai mai','kong bu zhu yi',
    'qiang zhi lao dong','jia hu zhao','mai huo yao',
    'qiang jian','xing qin hai','yu wei cheng nian ren xing jiao',
    'er tong luo ti','xia yao','lian tong pi','xing nu li',
    'mai bing du','mai da ma','mai yao tou wan',
    'gang xing','kou jiao','qiang po xing jiao',
    'qing shao nian xing','wei cheng nian luo ti',
    'mai ertong','xing ertong','luo ti ertong',
    '10 sui nv hai','10 sui nan hai','11 sui nv hai','11 sui nan hai',
    '12 sui nv hai','12 sui nan hai','13 sui nv hai','13 sui nan hai',
    '14 sui nv hai','14 sui nan hai','15 sui nv hai','15 sui nan hai',
    '16 sui nv hai','16 sui nan hai','17 sui nv hai','17 sui nan hai',
    // === HINDI (transliterated) ===
    'manav taskaree','nasheele padaarth bechna','hathiyaar bechna',
    'bachchon ka shoshan','aatankavaad','kale dhan ko safed karna',
    'supari dena','ang vyapaar',
    'balatkar','yaun shoshan','nabalik ke saath sambhog',
    'bachchon ki asheel tasveerein','nasheela karna',
    'yaun gulam','yaun taskaree',
    'yaun sambhog','muh mein sambhog','jabardasti sambhog',
    'kishor yaun','nabalik nagna',
    'ladki bechna','ladka bechna',
    '10 saal ladki','10 saal ladka','11 saal ladki','11 saal ladka',
    '12 saal ladki','12 saal ladka','13 saal ladki','13 saal ladka',
    '14 saal ladki','14 saal ladka','15 saal ladki','15 saal ladka',
    '16 saal ladki','16 saal ladka','17 saal ladki','17 saal ladka',
    // === JAPANESE (romaji) ===
    'jido poruno','mayaku hanbai','buki hanbai','jinshin baibai',
    'tero','maney rondaringu','satsujin iraisha','zoki baibai',
    'goukan','sei teki gyakutai','miseinen to no seikoi',
    'kusuri moru','sei dorei',
    'anaru sekusu','oaru sekusu',
    'miseinen sei','miseinen hadaka',
    'sei kodomo','hadaka kodomo','kodomo uru',
    '10 sai shoujo','10 sai shounen','11 sai shoujo','11 sai shounen',
    '12 sai shoujo','12 sai shounen','13 sai shoujo','13 sai shounen',
    '14 sai shoujo','14 sai shounen','15 sai shoujo','15 sai shounen',
    '16 sai shoujo','16 sai shounen','17 sai shoujo','17 sai shounen',
    // === KOREAN (romanized) ===
    'gangggan','seong hagdae','miseongnyeonja seong','aidong poreuno',
    'yaksul meogida','seong noye',
    'hang mun seong','gu gang seong',
    'cheongsonyon seong','miseongnyeon','seong ayi',
    '10 sal sonyeo','10 sal sonyeon','11 sal sonyeo','11 sal sonyeon',
    '12 sal sonyeo','12 sal sonyeon','13 sal sonyeo','13 sal sonyeon',
    '14 sal sonyeo','14 sal sonyeon','15 sal sonyeo','15 sal sonyeon',
    '16 sal sonyeo','16 sal sonyeon','17 sal sonyeo','17 sal sonyeon',
  ];
  for (const phrase of blocked) { if (lower.includes(phrase)) return 'Content rejected: prohibited phrase detected'; }
  return null;
}