// generated by make_chain.cjs — one entry per publishable chain game
// (static requires so Metro bundles every game's fragments)
module.exports = {
  'kascity-414-chain': { bundle: require('./chain_kascity-414-chain_bundle.json'), head: 'ef0c3a6ff34488044747589b3ee301c238879f496f60bf7bfb6c9fa7292ff63a', nonceBase: 9414 },
};
