// generated by make_chain.cjs — one entry per publishable chain game
// (static requires so Metro bundles every game's fragments)
module.exports = {
  'kascity-414-chain': { bundle: require('./chain_kascity-414-chain_bundle.json'), head: '976b8c49712ee5fd1e00a33e1042f6fd5ac24f3c135b4e1fca3a80010e476805', nonceBase: 9414 },
};
