// kascity_visual_v224.cjs — non-turn moves adopt instantly
// mgmt:*, cash:*, bid:*, p2pbuy, list/lapse/accept/refuse/counter, renovate are
// generated by the OWNER's client; the peer's engine can never independently
// produce them, so the drain sat asserting until the 30s force-adopt fired for
// every one (the residual stalls). Now: any remote move that isn't
// roll/buy/pass/first is adopted immediately — record written at the relay index
// with the mover's hash+snap, snapshot applied, queue advances.
const fs = require("fs");
const SRC = "showcase_kascity223.html";
const DST = "showcase_kascity224.html";
let s = fs.readFileSync(SRC, "utf8").replace(/\r\n/g, "\n");

if (s.indexOf("__KV_V224") !== -1) { console.error("ABORT: v224 already applied."); process.exit(1); }

const A1 = `    var turnBound=/^(roll|buy|pass|first)$/.test(String(m.a));
    if(turnBound && (f.seat||1)!==m.s){`;
const c = s.split(A1).length - 1;
if (c !== 1) { console.error("ABORT: anchor count " + c + " (expected 1). File untouched."); process.exit(1); }

s = s.replace(A1,
`    var turnBound=/^(roll|buy|pass|first)$/.test(String(m.a));
    // __KV_V224: owner-generated events (mgmt/cash/bid/p2pbuy/...) cannot be replayed
    // here — adopt them immediately instead of asserting for 30s.
    if(!turnBound){
      try{
        var mv4=(window.KV_MOVES||[]);
        if(!mv4[m.i]){ mv4[m.i]={ i:m.i, s:m.s, a:m.a, v:m.v, t:m.t, hash:m.hash||null, snap:m.snap||null }; }
        if(window.KV_ADOPT && m.snap) window.KV_ADOPT(m.snap);
        M.applying=m; applyRemote(m); setTimeout(function(){ if(M.applying===m) M.applying=null; }, 600);
        log("adopted "+m.a+" P"+m.s+" @"+m.i, "#9cd87c");
      }catch(e4){}
      M.queue.shift(); M.assertN=0; return;
    }
    if(turnBound && (f.seat||1)!==m.s){`);

fs.writeFileSync(DST, s);
console.log("PASS anchor 1/1 — non-turn remote moves adopt instantly");
console.log("OK " + DST + " (" + (fs.statSync(DST).size/1048576).toFixed(1) + " MB)");
