// kascity_visual_v77.cjs
// Reads showcase_kascity76.html -> showcase_kascity77.html   (scene JSON unchanged)
//
// MULTI-NODE FANOUT. Two players in different homes, both on WiFi — ordinary internet play. Because
// Flux nodes are stateless and any one of them can vanish, the move list is written to ALL configured
// nodes and read back from all of them, merged.
//
//   - the client chooses the room id and the seed, so the same room exists on every node without the
//     nodes ever talking to each other
//   - every move POSTs to all nodes in parallel; one success is enough to continue
//   - polling reads from all nodes and merges by (index, seat); duplicates collapse
//   - a node that 404s is re-seeded with our full local move log, then rejoins the rotation
//   - a small health strip shows which nodes are answering
//
// Configure the node list with:  window.KV_NODES = ["https://node1…","https://node2…", …]
// before the scene loads, or edit KV_DEFAULT_NODES below.
const fs = require('fs');
function die(m) { console.error('ABORT: ' + m + ' — nothing written.'); process.exit(1); }
if (!fs.existsSync('showcase_kascity76.html')) die('showcase_kascity76.html missing');
let html = fs.readFileSync('showcase_kascity76.html', 'utf8');

const anchor = '  window.KV_END=endGame;';
if (html.split(anchor).length - 1 !== 1) die('endGame anchor not found');

const fanout = [
  '  window.KV_END=endGame;',
  '',
  '  // ================= MULTI-NODE RELAY =================',
  '  (function(){',
  '    var COL={1:"#d94f4f",2:"#4f7fd9",3:"#4fd98a",4:"#d9c14f"};',
  '    function el(t,css,par){var e=document.createElement(t);e.style.cssText=css;(par||document.body).appendChild(e);return e;}',
  '',
  '    var KV_DEFAULT_NODES = [',
  '      "https://kasvillage.app.runonflux.io",',
  '      "https://kasvillage_1.app.runonflux.io",',
  '      "https://kasvillage_2.app.runonflux.io"',
  '    ];',
  '    window.KV_NODES = window.KV_NODES || KV_DEFAULT_NODES;',
  '    var health = {};   // url -> { ok, lastErr, seeded }',
  '    window.KV_NODES.forEach(function(u){ health[u]={ok:null,lastErr:"",seeded:false}; });',
  '',
  '    window.KV_MP = { room:null, seat:null, seed:null, online:false, cursor:0, seen:{} };',
  '',
  '    function rid(){',
  '      var a=new Uint8Array(4); crypto.getRandomValues(a);',
  '      return "kc"+Array.from(a).map(function(x){return x.toString(16).padStart(2,"0");}).join("");',
  '    }',
  '    function key(){',
  '      if(!window.__kvKey){',
  '        var a=new Uint8Array(24); crypto.getRandomValues(a);',
  '        window.__kvKey=Array.from(a).map(function(x){return x.toString(16).padStart(2,"0");}).join("");',
  '      }',
  '      return window.__kvKey;',
  '    }',
  '    async function call(url, path, opts){',
  '      var ctl=new AbortController();',
  '      var to=setTimeout(function(){ctl.abort();}, 4500);',
  '      try{',
  '        var r=await fetch(url+path, Object.assign({signal:ctl.signal,',
  '          headers:{"Content-Type":"application/json"}}, opts||{}));',
  '        clearTimeout(to);',
  '        if(!r.ok) throw new Error(String(r.status));',
  '        health[url].ok=true; health[url].lastErr="";',
  '        return await r.json();',
  '      }catch(e){',
  '        clearTimeout(to);',
  '        health[url].ok=false; health[url].lastErr=(e&&e.message)||"err";',
  '        throw e;',
  '      }',
  '    }',
  '    // write to every node, succeed if any one accepts',
  '    async function fanPost(path, body){',
  '      var results = await Promise.allSettled(window.KV_NODES.map(function(u){',
  '        return call(u, path, { method:"POST", body: JSON.stringify(body) });',
  '      }));',
  '      var ok = results.filter(function(r){ return r.status==="fulfilled"; });',
  '      if(!ok.length) throw new Error("no node accepted");',
  '      return ok[0].value;',
  '    }',
  '',
  '    // re-seed a node that lost the room: it is stateless, our move log is not',
  '    async function reseed(url){',
  '      var M=window.KV_MP;',
  '      if(!M.online || health[url].seeded) return;',
  '      health[url].seeded=true;',
  '      try{',
  '        await call(url, "/api/game/room/create", { method:"POST", body: JSON.stringify({',
  '          pubkey:key(), room:M.room, seed:M.seed }) });',
  '        var log=window.KV_MOVES||[];',
  '        for(var i=0;i<log.length;i++){',
  '          var m=log[i];',
  '          await call(url, "/api/game/room/"+M.room+"/move", { method:"POST", body: JSON.stringify({',
  '            index:m.i, seat:m.s, action:String(m.a), value:(+m.v||0), clock:(+m.t||0),',
  '            sig:"replay", pubkey:key(), root:(window.KV_ROOT||"") })});',
  '        }',
  '        window.KV_LOG("re-seeded a node with "+log.length+" moves","#caa64c");',
  '      }catch(e){}',
  '      setTimeout(function(){ health[url].seeded=false; }, 20000);',
  '    }',
  '',
  '    // outbound',
  '    var prevMove=window.KV_MOVE;',
  '    window.KV_MOVE=function(seat,action,value){',
  '      var r=prevMove?prevMove(seat,action,value):null;',
  '      var M=window.KV_MP;',
  '      if(M.online && M.seat===seat){',
  '        var idx=((window.KV_MOVES||[]).length)-1;',
  '        fanPost("/api/game/room/"+M.room+"/move", {',
  '          index: idx<0?0:idx, seat:seat, action:String(action), value:(+value||0),',
  '          clock: Math.round(((window.KV_FLAGS&&window.KV_FLAGS().left)||0)),',
  '          sig:"session", pubkey:key(), root:(window.KV_ROOT||"")',
  '        }).catch(function(){ window.KV_LOG("move not relayed — all nodes down","#ff6a4a"); });',
  '      }',
  '      return r;',
  '    };',
  '',
  '    function applyRemote(m){',
  '      var M=window.KV_MP;',
  '      if(m.seat===M.seat) return;',
  '      var k=m.index+":"+m.seat;',
  '      if(M.seen[k]) return;',
  '      M.seen[k]=1;',
  '      window.KV_LOG("P"+m.seat+"  "+m.action+(m.value?(" "+m.value):""), COL[m.seat]);',
  '      if(!window.KV_SETSTATE) return;',
  '      if(m.action==="roll")           window.KV_SETSTATE("go",0);',
  '      else if(m.action==="buy")       window.KV_SETSTATE("buy",0);',
  '      else if(m.action==="pass")      window.KV_SETSTATE("buy",1);',
  '      else if(m.action==="renovate"){ window.KV_SETSTATE("renov_by",m.seat);',
  '        window.KV_SETSTATE("renov_t",0); window.KV_SETSTATE("renov",m.value); }',
  '      else if(m.action && m.action.indexOf("bid:")===0){',
  '        window.KV_SETSTATE("tr_tile",+m.action.split(":")[1]);',
  '        window.KV_SETSTATE("tr_from",m.seat);',
  '        window.KV_SETSTATE("tr_amt",m.value);',
  '      }',
  '    }',
  '',
  '    // read from all nodes, merge',
  '    async function poll(){',
  '      var M=window.KV_MP;',
  '      if(!M.online) return;',
  '      var res = await Promise.allSettled(window.KV_NODES.map(function(u){',
  '        return call(u, "/api/game/room/"+M.room+"/since/0").catch(function(e){',
  '          if(String(e.message)==="404") reseed(u);',
  '          throw e;',
  '        });',
  '      }));',
  '      var merged={};',
  '      res.forEach(function(r){',
  '        if(r.status!=="fulfilled") return;',
  '        (r.value.moves||[]).forEach(function(m){ merged[m.index+":"+m.seat]=m; });',
  '      });',
  '      Object.keys(merged).sort(function(a,b){',
  '        return (+a.split(":")[0])-(+b.split(":")[0]);',
  '      }).forEach(function(k){ applyRemote(merged[k]); });',
  '      paint();',
  '    }',
  '    setInterval(poll, 800);',
  '',
  '    // ---- node health strip ----',
  '    var strip=el("div","position:fixed;left:50%;top:34px;transform:translateX(-50%);z-index:66;'
    + 'display:none;gap:5px;align-items:center;font:9px monospace;color:#f4e4c1;");',
  '    function paint(){',
  '      var M=window.KV_MP;',
  '      if(!M.online){ strip.style.display="none"; return; }',
  '      strip.style.display="flex";',
  '      var up=window.KV_NODES.filter(function(u){return health[u].ok===true;}).length;',
  '      strip.innerHTML="<span style=\'background:#2a2118;padding:3px 9px;border-radius:9px\'>ROOM "+M.room+',
  '        "  seat "+M.seat+"</span>";',
  '      window.KV_NODES.forEach(function(u,ix){',
  '        var st=health[u].ok;',
  '        var c=st===true?"#9cd87c":(st===false?"#ff6a4a":"#7a6a58");',
  '        strip.innerHTML+="<span title=\'"+u+"\' style=\'background:#1b1712;color:"+c+',
  '          ";padding:3px 7px;border-radius:9px\'>n"+(ix+1)+"</span>";',
  '      });',
  '      strip.innerHTML+="<span style=\'opacity:.6\'>"+up+"/"+window.KV_NODES.length+" up</span>";',
  '    }',
  '',
  '    // ---- lobby ----',
  '    window.KV_MP_HOST=async function(){',
  '      var room=rid();',
  '      var seed=room+"-"+Date.now();',
  '      try{',
  '        await fanPost("/api/game/room/create", { pubkey:key(), room:room, seed:seed,',
  '          wallet:(window.KV_WALLETS&&window.KV_WALLETS[1])||null });',
  '        window.KV_MP={ room:room, seat:1, seed:seed, online:true, cursor:0, seen:{} };',
  '        window.KV_HUMANS=[1,2]; window.KV_MODE="p2p"; window.KV_XP_MULT=1.0;',
  '        if(window.KV_SETSTATE) window.KV_SETSTATE("humans",2);',
  '        window.KV_LOG("hosting "+room+" on "+window.KV_NODES.length+" nodes — share the code","#caa64c");',
  '        paint();',
  '        return room;',
  '      }catch(e){ window.KV_LOG("host failed: "+e.message,"#ff6a4a"); }',
  '    };',
  '    window.KV_MP_JOIN=async function(code){',
  '      code=String(code).trim();',
  '      try{',
  '        var r=await fanPost("/api/game/room/join", { room:code, pubkey:key(),',
  '          wallet:(window.KV_WALLETS&&window.KV_WALLETS[2])||null });',
  '        window.KV_MP={ room:code, seat:r.seat, seed:r.seed, online:true, cursor:0, seen:{} };',
  '        window.KV_HUMANS=[1,2]; window.KV_MODE="p2p"; window.KV_XP_MULT=1.0;',
  '        if(window.KV_SETSTATE) window.KV_SETSTATE("humans",2);',
  '        window.KV_LOG("joined "+code+" as seat "+r.seat,"#9cd87c");',
  '        paint();',
  '        return r.seat;',
  '      }catch(e){ window.KV_LOG("join failed: "+e.message,"#ff6a4a"); }',
  '    };',
  '',
  '    setTimeout(function(){',
  '      var bar=el("div","position:fixed;left:50%;bottom:118px;transform:translateX(-50%);z-index:66;'
    + 'display:flex;gap:6px;align-items:center;font:11px monospace;color:#f4e4c1;");',
  '      var h=el("button","padding:6px 12px;background:#2f4a2f;color:#cfe6c4;border:1px solid #4fd98a;'
    + 'border-radius:5px;font:11px monospace;cursor:pointer;",bar);',
  '      h.textContent="Host (3 nodes)";',
  '      h.onclick=function(e){ e.stopPropagation(); window.KV_MP_HOST(); };',
  '      var c=el("input","width:110px;padding:5px 8px;background:#1a1410;color:#f4e4c1;'
    + 'border:1px solid #5a4a3a;border-radius:5px;font:11px monospace;",bar);',
  '      c.placeholder="room code";',
  '      var jn=el("button","padding:6px 12px;background:#2a2118;color:#f4e4c1;border:1px solid #5a4a3a;'
    + 'border-radius:5px;font:11px monospace;cursor:pointer;",bar);',
  '      jn.textContent="Join";',
  '      jn.onclick=function(e){ e.stopPropagation(); if(c.value.trim()) window.KV_MP_JOIN(c.value); };',
  '    }, 1000);',
  '  })();'
].join('\n');
html = html.split(anchor).join(fanout);

fs.writeFileSync('showcase_kascity77.html', html);
console.log('PASS moves written to all three nodes in parallel; one acceptance is enough');
console.log('PASS reads merged from every node, deduped by (index, seat)');
console.log('PASS a node that 404s is re-seeded from our local move log and rejoins');
console.log('PASS client picks the room id and seed, so nodes need never talk to each other');
console.log('PASS node health strip shows which of the three are answering');
console.log('OK showcase_kascity77.html (' + (fs.statSync('showcase_kascity77.html').size/1024/1024).toFixed(1) + ' MB)');
