// kascity_visual_v167.cjs
// Reads showcase_kascity166.html -> showcase_kascity167.html
// Console toolkit. Adds a set of KV.* commands you can run in the browser console (F12) to inspect
// and drive the game without hunting through the UI. Type KV.help() for the list.
const fs = require('fs');
function die(m) { console.error('ABORT: ' + m + ' — nothing written.'); process.exit(1); }
if (!fs.existsSync('showcase_kascity166.html')) die('showcase_kascity166.html missing');
let html = fs.readFileSync('showcase_kascity166.html', 'utf8');
const EOL = html.indexOf('\r\n') >= 0 ? '\r\n' : '\n';
const anchor = '// ---- divergence checksum (v166) ----';
if (html.split(anchor).length - 1 !== 1) die('anchor not unique');

const K = [
'// ---- console toolkit (v167) ----',
'(function(){',
'  function W(){ return window.KV_WORLD || null; }',
'  function F(){ return (window.KV_FLAGS && window.KV_FLAGS()) || {}; }',
'  function cash(p){ var w=W(); return (w&&w.seats&&w.seats[p-1]) ? Math.round(w.seats[p-1].cash||0) : null; }',
'  function nm(t){ var N=window.KV_NAMES||{}; return (N[t]&&N[t].n)||("tile "+t); }',
'  function owners(){ var w=W(), o={}; if(!w||!w.owners) return o;',
'    Object.keys(w.owners).forEach(function(k){ var t=+String(k).replace("t",""); if(w.owners[k]) o[t]=w.owners[k]; }); return o; }',
'',
'  var KV = {',
'    help: function(){ console.log([',
'      "KV.state()      board summary: turn, seat, clock, phase, cash, holdings",',
'      "KV.money()      every seat: cash, property value, net worth",',
'      "KV.owners()     who owns what, by tile",',
'      "KV.me()         your seat, cash, blocks, XP",',
'      "KV.tile(n)      one block: name, owner, price, rent, hazard, listing",',
'      "KV.flags(re)    engine flags, optionally filtered  e.g. KV.flags(/tr_|htr_/)",',
'      "KV.moves(n)     last n moves from the record (default 20)",',
'      "KV.net()        multiplayer: room, seat, peers, cursor, drift",',
'      "KV.sum()        state checksum used for divergence detection",',
'      "KV.trace(on)    verbose settlement trace on/off",',
'      "KV.pay(t,b,s,a) force a settlement (testing)",',
'      "KV.give(p,amt)  adjust a seat cash (testing)",',
'      "KV.host()       host a room     KV.join(code)  join one",',
'      "KV.watch(on)    live one-line status every second"',
'    ].join("\\n")); return "type any of the above"; },',
'',
'    state: function(){ var f=F(); var o=owners(); var c={};',
'      for(var p=1;p<=4;p++) c["P"+p]=cash(p);',
'      var h={1:[],2:[],3:[],4:[]}; Object.keys(o).forEach(function(t){ h[o[t]].push(+t); });',
'      var out={ turn:f.turn, seat:f.seat, clockLeft:Math.round(f.left||0), phase:f.phase,',
'        humans:f.humans, cash:c, blocks:{P1:h[1].length,P2:h[2].length,P3:h[3].length,P4:h[4].length} };',
'      console.table(out.cash); console.log(out); return out; },',
'',
'    money: function(){ var rows=[]; var o=owners();',
'      for(var p=1;p<=4;p++){ var pv=0; Object.keys(o).forEach(function(t){ if(o[t]===p) pv+=(window.KV_MARKET?window.KV_MARKET(+t):0)||0; });',
'        rows.push({ seat:"P"+p, cash:cash(p), propertyValue:Math.round(pv), netWorth:Math.round((cash(p)||0)+pv) }); }',
'      console.table(rows); return rows; },',
'',
'    owners: function(){ var o=owners(), rows=[];',
'      Object.keys(o).map(Number).sort(function(a,b){return a-b;}).forEach(function(t){',
'        rows.push({ tile:t, name:nm(t), owner:"P"+o[t], value:(window.KV_MARKET?Math.round(window.KV_MARKET(t)):"-") }); });',
'      console.table(rows); return rows; },',
'',
'    me: function(){ var s=(window.KV_NET&&window.KV_NET.seat)||(window.KV_HUMANS||[1])[0]||1;',
'      var o=owners(), mine=[]; Object.keys(o).forEach(function(t){ if(o[t]===s) mine.push(nm(+t)); });',
'      var r={ seat:"P"+s, cash:cash(s), xp:(window.KV_XP&&window.KV_XP[s])||0, blocks:mine };',
'      console.log(r); return r; },',
'',
'    tile: function(t){ var f=F(), o=owners();',
'      var r={ tile:t, name:nm(t), owner:o[t]?("P"+o[t]):"unowned",',
'        market:(window.KV_MARKET?Math.round(window.KV_MARKET(t)):"-"),',
'        fair:(window.KV_INTRINSIC?Math.round(window.KV_INTRINSIC(t)):"-"),',
'        age:f["age_t"+t], tax:f["tax_t"+t], hazard:f["hz_t"+t], renovations:f["rv_t"+t],',
'        listed:(f["ls_t"+t]?("yes at "+f["lp_t"+t]):"no"),',
'        holdLeft:(window.KV_HOLD_LEFT?window.KV_HOLD_LEFT(t):0) };',
'      console.log(r); return r; },',
'',
'    flags: function(re){ var f=F(), out={};',
'      Object.keys(f).sort().forEach(function(k){ if(!re || re.test(k)) out[k]=f[k]; });',
'      console.log(out); return out; },',
'',
'    moves: function(n){ n=n||20; var m=(window.KV_MOVES||[]).slice(-n);',
'      console.table(m.map(function(x){ return { i:x.i, seat:"P"+x.s, action:x.a, value:x.v, t:x.t }; })); return m; },',
'',
'    net: function(){ var N=window.KV_NET||{};',
'      var r={ online:!!N.online, room:N.room||"-", seat:N.seat||"-", peers:N.peerSeen||0,',
'        cursor:N.cursor, diverged:!!N.diverged, mode:window.KV_MODE, humans:(window.KV_HUMANS||[]).join(",") };',
'      console.log(r); return r; },',
'',
'    sum: function(){ var s=window.KV_STATESUM?window.KV_STATESUM():""; console.log(s); return s; },',
'',
'    trace: function(on){ window.__TR_VERBOSE = (on!==false); return "settlement trace "+(window.__TR_VERBOSE?"ON":"OFF"); },',
'',
'    pay: function(t,b,s,a){ if(!window.KV_PAY) return "KV_PAY missing";',
'      var r=window.KV_PAY(t,b,s,a); console.log(r); return r; },',
'',
'    give: function(p,amt){ var w=W(); if(!w||!w.seats) return "no world";',
'      w.seats[p-1]=w.seats[p-1]||{}; w.seats[p-1].cash=(w.seats[p-1].cash||0)+amt;',
'      return "P"+p+" cash now "+Math.round(w.seats[p-1].cash); },',
'',
'    host: function(){ return window.KV_HOST ? window.KV_HOST() : "no KV_HOST"; },',
'    join: function(c){ return window.KV_JOIN ? window.KV_JOIN(c) : "no KV_JOIN"; },',
'',
'    watch: function(on){',
'      if(window.__kvWatch){ clearInterval(window.__kvWatch); window.__kvWatch=null; }',
'      if(on===false) return "watch off";',
'      window.__kvWatch=setInterval(function(){ var f=F();',
'        console.log("t"+Math.round(f.left||0)+"s seat P"+f.seat+" phase "+f.phase+"  cash "+',
'          [1,2,3,4].map(function(p){return "P"+p+":"+cash(p);}).join(" ")); }, 1000);',
'      return "watch on (KV.watch(false) to stop)"; }',
'  };',
'  window.KV = KV;',
'  console.log("%cKasCity console ready \\u2014 type KV.help()", "color:#f0c860;font-weight:700");',
'})();',
''
].join(EOL);

html = html.replace(anchor, K + EOL + anchor);
console.log('PASS console toolkit installed (KV.help)');
fs.writeFileSync('showcase_kascity167.html', html);
console.log('OK showcase_kascity167.html (' + (fs.statSync('showcase_kascity167.html').size/1024/1024).toFixed(1) + ' MB)');
