// make_devtools.cjs — writes devtools.html AND devtools_inject.js
//   devtools.html: the engine + a full toolbench (inspector / pose editor / profiler)
//   devtools_inject.js: the same panel as a standalone snippet a dev can paste
//     into any showcase before </script>.
// Panels:
//   INSPECT  live node tree; click a node to see and edit transform, hp, stance,
//            tags; toggle visibility; ragdoll it; teleport to it.
//   POSE     bone sliders for the selected rigged actor; capture keyframes at a
//            time cursor; EXPORT prints ready-to-paste clip JSON.
//   PROF     frame time graph, draw counts, body/ragdoll/projectile counts,
//            per-system millisecond breakdown.
const fs = require("fs");
const engine = fs.readFileSync("scene_engine.html", "utf8");
const q = String.fromCharCode(39);

const panel = [
  "// ---- KV DEVTOOLS ----",
  "(function () {",
  "  var BONES = [" + q + "torso" + q + "," + q + "head" + q + "," + q + "armL" + q + "," + q + "foreL" + q + "," + q + "armR" + q + "," + q + "foreR" + q + "," + q + "legL" + q + "," + q + "shinL" + q + "," + q + "legR" + q + "," + q + "shinR" + q + "," + q + "weapon" + q + "];",
  "  var sel = null, tab = " + q + "inspect" + q + ", keys = [], cursor = 0, live = {};",
  "  var root = document.createElement(" + q + "div" + q + ");",
  "  root.style.cssText = " + q + "position:fixed;top:0;right:0;bottom:0;width:330px;background:rgba(12,15,18,0.96);color:#cfe;z-index:99999;font-family:monospace;font-size:11px;display:flex;flex-direction:column;border-left:2px solid #2a3138" + q + ";",
  "  var tabs = document.createElement(" + q + "div" + q + ");",
  "  tabs.style.cssText = " + q + "display:flex;border-bottom:1px solid #2a3138" + q + ";",
  "  var body = document.createElement(" + q + "div" + q + ");",
  "  body.style.cssText = " + q + "flex:1;overflow:auto;padding:6px" + q + ";",
  "  root.appendChild(tabs); root.appendChild(body);",
  "  document.body.appendChild(root);",
  "  function mkTab(id, label) {",
  "    var b = document.createElement(" + q + "button" + q + ");",
  "    b.textContent = label;",
  "    b.style.cssText = " + q + "flex:1;padding:7px;background:#1a2026;color:#cfe;border:0;border-right:1px solid #2a3138;font-family:monospace;font-size:11px" + q + ";",
  "    b.onclick = function () { tab = id; draw(); };",
  "    tabs.appendChild(b);",
  "  }",
  "  mkTab(" + q + "inspect" + q + "," + q + "INSPECT" + q + ");",
  "  mkTab(" + q + "pose" + q + "," + q + "POSE" + q + ");",
  "  mkTab(" + q + "prof" + q + "," + q + "PROF" + q + ");",
  "  var hide = document.createElement(" + q + "button" + q + ");",
  "  hide.textContent = " + q + "×" + q + ";",
  "  hide.style.cssText = " + q + "width:28px;background:#3a2026;color:#fcc;border:0;font-family:monospace" + q + ";",
  "  hide.onclick = function () { root.style.display = root.style.display === " + q + "none" + q + " ? " + q + "flex" + q + " : " + q + "none" + q + "; };",
  "  tabs.appendChild(hide);",
  "  function row(label, val, onEdit) {",
  "    var d = document.createElement(" + q + "div" + q + ");",
  "    d.style.cssText = " + q + "display:flex;justify-content:space-between;padding:1px 0" + q + ";",
  "    var a = document.createElement(" + q + "span" + q + "); a.textContent = label; a.style.color = " + q + "#7a9" + q + ";",
  "    d.appendChild(a);",
  "    if (onEdit) {",
  "      var inp = document.createElement(" + q + "input" + q + ");",
  "      inp.value = val; inp.style.cssText = " + q + "width:120px;background:#0c1014;color:#cfe;border:1px solid #2a3138;font-family:monospace;font-size:11px" + q + ";",
  "      inp.onchange = function () { onEdit(inp.value); };",
  "      d.appendChild(inp);",
  "    } else { var b2 = document.createElement(" + q + "span" + q + "); b2.textContent = val; d.appendChild(b2); }",
  "    body.appendChild(d);",
  "  }",
  "  function btn(label, fn, col) {",
  "    var b = document.createElement(" + q + "button" + q + ");",
  "    b.textContent = label;",
  "    b.style.cssText = " + q + "margin:2px 2px 2px 0;padding:4px 7px;background:" + q + " + (col || " + q + "#1f2731" + q + ") + " + q + ";color:#cfe;border:1px solid #2a3138;font-family:monospace;font-size:11px" + q + ";",
  "    b.onclick = fn;",
  "    body.appendChild(b);",
  "    return b;",
  "  }",
  "  function head(txt) {",
  "    var h = document.createElement(" + q + "div" + q + ");",
  "    h.textContent = txt;",
  "    h.style.cssText = " + q + "color:#8fd;margin:6px 0 3px;border-bottom:1px solid #2a3138" + q + ";",
  "    body.appendChild(h);",
  "  }",
  "  function drawInspect() {",
  "    head(" + q + "NODES (" + q + " + Object.keys(nodes).length + " + q + ")" + q + ");",
  "    var ids = Object.keys(nodes);",
  "    var list = document.createElement(" + q + "div" + q + ");",
  "    list.style.cssText = " + q + "max-height:150px;overflow:auto;margin-bottom:5px" + q + ";",
  "    ids.forEach(function (id) {",
  "      var n = nodes[id];",
  "      var e = document.createElement(" + q + "div" + q + ");",
  "      e.textContent = (n._geo && n._geo.rigged ? " + q + "* " + q + " : " + q + "  " + q + ") + id + " + q + "  [" + q + " + (n.type || " + q + "?" + q + ") + " + q + "]" + q + ";",
  "      e.style.cssText = " + q + "cursor:pointer;padding:1px 3px;" + q + " + (sel === id ? " + q + "background:#24404a;color:#dff" + q + " : " + q + "" + q + ");",
  "      e.onclick = function () { sel = id; draw(); };",
  "      list.appendChild(e);",
  "    });",
  "    body.appendChild(list);",
  "    if (!sel || !nodes[sel]) return;",
  "    var n = nodes[sel];",
  "    head(" + q + "SELECTED: " + q + " + sel);",
  "    var t = n.transform || { pos: [0, 0, 0], rot: [0, 0, 0] };",
  "    row(" + q + "pos x" + q + ", t.pos[0].toFixed(2), function (v) { t.pos[0] = parseFloat(v); });",
  "    row(" + q + "pos y" + q + ", t.pos[1].toFixed(2), function (v) { t.pos[1] = parseFloat(v); });",
  "    row(" + q + "pos z" + q + ", t.pos[2].toFixed(2), function (v) { t.pos[2] = parseFloat(v); });",
  "    row(" + q + "rot y" + q + ", (t.rot ? t.rot[1] : 0).toFixed(1), function (v) { t.rot[1] = parseFloat(v); });",
  "    if (n.stats) row(" + q + "hp" + q + ", (n.hp != null ? n.hp : " + q + "-" + q + ") + " + q + "/" + q + " + n.stats.maxHp, function (v) { n.hp = parseFloat(v); });",
  "    if (n.stance != null) row(" + q + "stance" + q + ", n.stance, function (v) { n.stance = v; });",
  "    row(" + q + "tags" + q + ", (n.tags || []).join(" + q + "," + q + "));",
  "    row(" + q + "room" + q + ", n.room || " + q + "-" + q + ");",
  "    btn(" + q + "VISIBLE" + q + ", function () { n.visible = n.visible === false; });",
  "    btn(" + q + "RAGDOLL" + q + ", function () { if (typeof startRagdoll === " + q + "function" + q + ") startRagdoll(n, { x: 2, y: 4, z: 0 }); });",
  "    btn(" + q + "TP PLAYER HERE" + q + ", function () {",
  "      var pl = nodes[playerId];",
  "      if (pl) { pl.transform.pos[0] = t.pos[0] + 1.5; pl.transform.pos[2] = t.pos[2]; }",
  "    });",
  "    btn(" + q + "LOCK ON" + q + ", function () { LOCK.target = sel; });",
  "  }",
  "  function drawPose() {",
  "    var n = sel ? nodes[sel] : null;",
  "    if (!n || !n._geo || !n._geo.rigged) { head(" + q + "select a rigged actor in INSPECT" + q + "); return; }",
  "    head(" + q + "POSE EDITOR: " + q + " + sel);",
  "    row(" + q + "time" + q + ", cursor.toFixed(2), function (v) { cursor = parseFloat(v) || 0; });",
  "    BONES.forEach(function (bn) {",
  "      if (!n._geo.parts[bn]) return;",
  "      var d = document.createElement(" + q + "div" + q + ");",
  "      d.style.cssText = " + q + "margin:2px 0" + q + ";",
  "      var lab = document.createElement(" + q + "div" + q + ");",
  "      live[bn] = live[bn] || { rx: 0, ry: 0, rz: 0 };",
  "      lab.textContent = bn + " + q + "  rx" + q + " + live[bn].rx.toFixed(0) + " + q + " ry" + q + " + live[bn].ry.toFixed(0) + " + q + " rz" + q + " + live[bn].rz.toFixed(0);",
  "      lab.style.color = " + q + "#7a9" + q + ";",
  "      d.appendChild(lab);",
  "      [" + q + "rx" + q + "," + q + "ry" + q + "," + q + "rz" + q + "].forEach(function (ax) {",
  "        var s = document.createElement(" + q + "input" + q + ");",
  "        s.type = " + q + "range" + q + "; s.min = -180; s.max = 180; s.step = 1; s.value = live[bn][ax];",
  "        s.style.cssText = " + q + "width:100%;height:12px" + q + ";",
  "        s.oninput = function () {",
  "          live[bn][ax] = parseFloat(s.value);",
  "          n._devPose = {};",
  "          for (var k in live) n._devPose[k] = { rx: live[k].rx, ry: live[k].ry, rz: live[k].rz };",
  "          lab.textContent = bn + " + q + "  rx" + q + " + live[bn].rx.toFixed(0) + " + q + " ry" + q + " + live[bn].ry.toFixed(0) + " + q + " rz" + q + " + live[bn].rz.toFixed(0);",
  "        };",
  "        d.appendChild(s);",
  "      });",
  "      body.appendChild(d);",
  "    });",
  "    btn(" + q + "CAPTURE KEY @ " + q + " + cursor.toFixed(2), function () {",
  "      var snap = {};",
  "      for (var k in live) if (live[k].rx || live[k].ry || live[k].rz) snap[k] = { rx: live[k].rx, ry: live[k].ry, rz: live[k].rz };",
  "      keys.push({ t: cursor, pose: snap });",
  "      cursor = Math.round((cursor + 0.15) * 100) / 100;",
  "      draw();",
  "    }, " + q + "#25402c" + q + ");",
  "    btn(" + q + "RESET BONES" + q + ", function () { live = {}; if (nodes[sel]) nodes[sel]._devPose = null; draw(); });",
  "    btn(" + q + "CLEAR KEYS" + q + ", function () { keys = []; cursor = 0; draw(); });",
  "    head(" + q + "KEYS (" + q + " + keys.length + " + q + ")" + q + ");",
  "    keys.forEach(function (k, i) { row(" + q + "t=" + q + " + k.t.toFixed(2), Object.keys(k.pose).join(" + q + "," + q + ") || " + q + "(rest)" + q + "); });",
  "    btn(" + q + "EXPORT CLIP JSON" + q + ", function () {",
  "      var tracks = {};",
  "      keys.forEach(function (k) {",
  "        for (var bn in k.pose) {",
  "          tracks[bn] = tracks[bn] || [[0, 0]];",
  "          tracks[bn].push([k.t, k.pose[bn]]);",
  "        }",
  "      });",
  "      var dur = keys.length ? keys[keys.length - 1].t + 0.15 : 0.5;",
  "      for (var bn2 in tracks) tracks[bn2].push([dur, 0]);",
  "      var clip = { dur: Math.round(dur * 100) / 100, loop: false, blendIn: 0.08, tracks: tracks };",
  "      var ta = document.createElement(" + q + "textarea" + q + ");",
  "      ta.value = JSON.stringify(clip, null, 2);",
  "      ta.style.cssText = " + q + "width:100%;height:170px;background:#0c1014;color:#9fe8a0;border:1px solid #2a3138;font-family:monospace;font-size:10px" + q + ";",
  "      body.appendChild(ta);",
  "      ta.select();",
  "    }, " + q + "#2a3550" + q + ");",
  "  }",
  "  var ftimes = [], lastT = performance.now();",
  "  function drawProf() {",
  "    head(" + q + "PROFILER" + q + ");",
  "    var avg = 0;",
  "    for (var i = 0; i < ftimes.length; i++) avg += ftimes[i];",
  "    avg = ftimes.length ? avg / ftimes.length : 0;",
  "    row(" + q + "frame ms" + q + ", avg.toFixed(2));",
  "    row(" + q + "fps" + q + ", (avg > 0 ? (1000 / avg).toFixed(0) : " + q + "-" + q + "));",
  "    row(" + q + "nodes" + q + ", Object.keys(nodes).length);",
  "    row(" + q + "actors" + q + ", typeof actors !== " + q + "undefined" + q + " ? actors.length : 0);",
  "    row(" + q + "bodies" + q + ", typeof BODIES !== " + q + "undefined" + q + " ? BODIES.length : 0);",
  "    var awake = 0;",
  "    if (typeof BODIES !== " + q + "undefined" + q + ") for (var b = 0; b < BODIES.length; b++) if (!BODIES[b].asleep) awake++;",
  "    row(" + q + "awake" + q + ", awake);",
  "    row(" + q + "ragdolls" + q + ", typeof RAGDOLLS !== " + q + "undefined" + q + " ? RAGDOLLS.length : 0);",
  "    row(" + q + "projectiles" + q + ", typeof PROJECTILES !== " + q + "undefined" + q + " ? PROJECTILES.length : 0);",
  "    row(" + q + "joints" + q + ", typeof JOINTS !== " + q + "undefined" + q + " ? JOINTS.length : 0);",
  "    row(" + q + "posed" + q + ", typeof POSED !== " + q + "undefined" + q + " ? POSED.length : 0);",
  "    row(" + q + "room" + q + ", scene._room || " + q + "-" + q + ");",
  "    var cv = document.createElement(" + q + "canvas" + q + ");",
  "    cv.width = 300; cv.height = 60;",
  "    cv.style.cssText = " + q + "margin-top:6px;background:#0c1014;border:1px solid #2a3138;width:100%" + q + ";",
  "    body.appendChild(cv);",
  "    var g = cv.getContext(" + q + "2d" + q + ");",
  "    g.strokeStyle = " + q + "#6fd" + q + "; g.beginPath();",
  "    for (var f = 0; f < ftimes.length; f++) {",
  "      var yy = 60 - Math.min(60, ftimes[f] * 2);",
  "      if (f === 0) g.moveTo(0, yy); else g.lineTo(f * (300 / 60), yy);",
  "    }",
  "    g.stroke();",
  "    g.strokeStyle = " + q + "#e66" + q + ";",
  "    g.beginPath(); g.moveTo(0, 60 - 16.7 * 2); g.lineTo(300, 60 - 16.7 * 2); g.stroke();",
  "  }",
  "  function draw() {",
  "    body.innerHTML = " + q + "" + q + ";",
  "    if (tab === " + q + "inspect" + q + ") drawInspect();",
  "    else if (tab === " + q + "pose" + q + ") drawPose();",
  "    else drawProf();",
  "  }",
  "  setInterval(function () {",
  "    var now = performance.now();",
  "    ftimes.push(now - lastT);",
  "    if (ftimes.length > 60) ftimes.shift();",
  "    lastT = now;",
  "  }, 16);",
  "  setInterval(function () { if (tab !== " + q + "pose" + q + ") draw(); }, 700);",
  "  if (typeof FRAME_HOOKS !== " + q + "undefined" + q + ") {",
  "    FRAME_HOOKS.push(function () {",
  "      if (!sel || !nodes[sel] || !nodes[sel]._devPose) return;",
  "      var n = nodes[sel];",
  "      n._addPose = null;",
  "      n._devApply = 1;",
  "    });",
  "  }",
  "  draw();",
  "})();"
].join("\n");

fs.writeFileSync("devtools_inject.js", panel);

const marker = "</script>";
const idx = engine.lastIndexOf(marker);
if (idx < 0) { console.error("ABORT: no </scr" + "ipt>"); process.exit(1); }
// devtools.html: village scene + the panel
const scene = {
  kind: "kv_game_v1", engine: "scene",
  meta: { id: "devtools", title: "devtools", seed: "dt1", debug: true },
  render: { vertexSnap: 1, gouraud: true, shadows: true, cameraBlend: 0.3,
    fog: { enabled: true, near: 12, far: 40, color: "#12181f" },
    post: { enabled: true, scanAlpha: 0.05 } },
  nodes: [
    { id: "cam", type: "Camera3D", mode: "fixed", fov: 50, transform: { pos: [0, 4, 12] } },
    { id: "hero", type: "Actor", mesh: "body", tags: ["player"], transform: { pos: [0, 0, 3] },
      stats: { hp: 30, maxHp: 30, speed: 4 }, ragdoll: { enabled: true } },
    { id: "orc", type: "Actor", mesh: "orcBody", tags: ["enemy"], transform: { pos: [2.5, 0, -1] },
      stats: { hp: 40, maxHp: 40 }, ragdoll: { enabled: true }, headLook: { target: "hero" } },
    { id: "ground", type: "MeshInstance", mesh: "slab", material: "ground", transform: { pos: [0, -0.12, 0] } },
    { id: "crate", type: "MeshInstance", mesh: "crateM", material: "wood",
      physics: { body: "dynamic", shape: "box", half: [0.5, 0.5, 0.5], mass: 2 },
      transform: { pos: [-2, 2, -1] } },
    { id: "tree", type: "MeshInstance", mesh: "t", material: "leaf", transform: { pos: [-5, 0, -5] } }
  ],
  resources: {
    meshes: {
      body: { type: "silhouette", generator: "humanoid" },
      orcBody: { type: "silhouette", generator: "humanoid", race: "orc", held: { type: "club" } },
      slab: { type: "box", size: [30, 0.24, 30] }, crateM: { type: "crate" }, t: { type: "tree" }
    },
    materials: { ground: { color: "#3a4438" }, wood: { color: "#7a5a3a" }, leaf: { color: "#3f7a44" } }
  }
};
const inject = "\ntry { loadScene(" + JSON.stringify(JSON.stringify(scene)) + "); } catch (e) { document.title = " + q + "ERR " + q + " + e.message; }\n" + panel + "\n";
fs.writeFileSync("devtools.html", engine.slice(0, idx) + inject + engine.slice(idx));
console.log("OK devtools.html (inspector / pose editor / profiler)");
console.log("OK devtools_inject.js — paste into any showcase before the closing script tag");
