const fs = require('fs');
const p = 'NeighborAgreement.tsx';
let src = fs.readFileSync(p, 'utf8');
function die(m){ console.error('[Abort] ABORT-PATCH - ' + m + ' (nothing written)'); process.exit(1); }
const Q = String.fromCharCode(39); // single quote, avoids here-string escaping issues

// Anchor: reclaim button tail (unique). Span the {contract.timeoutMinutes ?? 5} braces literally.
const anchorRe = /Only if the buyer never funds, after \{contract\.timeoutMinutes \?\? 5\} min<\/Text>\r?\n\s*<\/TouchableOpacity>\r?\n\s*\)\}/;
const hits = (src.match(new RegExp(anchorRe.source, 'g')) || []).length;
if (hits !== 1) die('reclaim-tail anchor: expected 1 match, found ' + hits);
const m = src.match(anchorRe);
const anchorText = m[0];
const EOL = anchorText.includes('\r\n') ? '\r\n' : '\n';

const L = [];
L.push('');
L.push('                    {/* 5f: ABORT PENDING AGREEMENT - buyer never returned the co-signature. */}');
L.push('                    {role === ' + Q + 'seller' + Q + ' && contract.agreementId && (');
L.push('                      <TouchableOpacity');
L.push('                        onPress={async () => {');
L.push('                          const _agrId = contract.agreementId || ' + Q + Q + ';');
L.push('                          try {');
L.push('                            const _pj = await SecureStore.getItemAsync(' + Q + 'kv_refund_pending_' + Q + ' + _agrId);');
L.push('                            if (!_pj) { Alert.alert(' + Q + 'Nothing Pending' + Q + ', ' + Q + 'No frozen collateral is waiting on a buyer co-signature for this agreement.' + Q + '); return; }');
L.push('                            const _pp = JSON.parse(_pj);');
L.push('                            // SAFETY GATE: abort is only legal while NOTHING is on-chain. If the escrow');
L.push('                            // has any UTXO, the funding tx was broadcast - this is a live agreement and');
L.push('                            // the ledger tag must NOT be released; use Reclaim (after timeout) or Release.');
L.push('                            const _net = String(_pp.network || ' + Q + 'testnet-10' + Q + ');');
L.push('                            const _api = _net.includes(' + Q + 'testnet' + Q + ') ? ' + Q + 'https://api-tn10.kaspa.org' + Q + ' : ' + Q + 'https://api.kaspa.org' + Q + ';');
L.push('                            const _fr = _pp.frostAddr || contract.multisigAddress || ' + Q + Q + ';');
L.push('                            if (!_fr || _fr.length < 20) { Alert.alert(' + Q + 'Error' + Q + ', ' + Q + 'Pending record has no escrow address - cannot verify safety. Not touching anything.' + Q + '); return; }');
L.push('                            const _ur = await fetch(_api + ' + Q + '/addresses/' + Q + ' + _fr + ' + Q + '/utxos' + Q + ');');
L.push('                            if (!_ur.ok) { Alert.alert(' + Q + 'Error' + Q + ', ' + Q + 'Could not check the escrow on L1. Not touching anything - try again.' + Q + '); return; }');
L.push('                            const _uu = await _ur.json();');
L.push('                            if (Array.isArray(_uu) && _uu.length > 0) {');
L.push('                              Alert.alert(' + Q + 'Cannot Abort' + Q + ', ' + Q + 'The escrow already holds funds on-chain, so this is a live agreement. Aborting now would strand real collateral. Use Reclaim (after the timeout) or a mutual release instead.' + Q + ');');
L.push('                              return;');
L.push('                            }');
L.push('                            Alert.alert(' + Q + 'Abort Pending Agreement?' + Q + ', ' + Q + 'The buyer never returned their co-signature and nothing was sent on-chain. This frees your reserved ' + Q + ' + (Number(_pp.amountSompi || 0) / 1e8) + ' + Q + ' KAS and deletes the frozen (unsigned) refund. The agreement cannot be resumed after this.' + Q + ', [');
L.push('                              { text: ' + Q + 'Keep Waiting' + Q + ', style: ' + Q + 'cancel' + Q + ' },');
L.push('                              { text: ' + Q + 'Abort & Free Funds' + Q + ', style: ' + Q + 'destructive' + Q + ', onPress: async () => {');
L.push('                                try {');
L.push('                                  setIsLoading(true);');
L.push('                                  try { await releaseCommitment(_agrId); console.log(' + Q + '[Abort] Released UTXO tags for' + Q + ', _agrId); } catch (e) { console.warn(' + Q + '[Abort] releaseCommitment failed:' + Q + ', e); }');
L.push('                                  await SecureStore.deleteItemAsync(' + Q + 'kv_refund_pending_' + Q + ' + _agrId).catch(() => {});');
L.push('                                  await removeFrostEntry(_agrId).catch(() => {});');
L.push('                                  await archiveAgreementSession(' + Q + 'aborted-pending' + Q + ').catch(() => {});');
L.push('                                  await clearAgreementSession().catch(() => {});');
L.push('                                  Alert.alert(' + Q + 'Aborted' + Q + ', ' + Q + 'Reservation released. Your funds are spendable again. Nothing was ever sent on-chain.' + Q + ');');
L.push('                                  setStep(1); setRole(null); setAgreementType(null);');
L.push('                                } catch (e) {');
L.push('                                  console.error(' + Q + '[Abort] Error:' + Q + ', e);');
L.push('                                  Alert.alert(' + Q + 'Error' + Q + ', e instanceof Error ? e.message : ' + Q + 'Abort failed' + Q + ');');
L.push('                                } finally { setIsLoading(false); }');
L.push('                              }},');
L.push('                            ]);');
L.push('                          } catch (e) {');
L.push('                            console.error(' + Q + '[Abort] Check failed:' + Q + ', e);');
L.push('                            Alert.alert(' + Q + 'Error' + Q + ', e instanceof Error ? e.message : ' + Q + 'Abort check failed' + Q + ');');
L.push('                          }');
L.push('                        }}');
L.push('                        style={{ backgroundColor: ' + Q + '#fef2f2' + Q + ', borderWidth: 2, borderColor: ' + Q + '#dc2626' + Q + ', borderRadius: 12, paddingVertical: 12, alignItems: ' + Q + 'center' + Q + ', marginBottom: 16 }}');
L.push('                      >');
L.push('                        <Text style={{ fontSize: rs.font(13), fontWeight: ' + Q + 'bold' + Q + ', color: ' + Q + '#991b1b' + Q + ' }}>Abort Pending Agreement</Text>');
L.push('                        <Text style={{ fontSize: rs.font(9), color: ' + Q + '#b91c1c' + Q + ', marginTop: 2 }}>Only if the buyer never co-signed and nothing was sent</Text>');
L.push('                      </TouchableOpacity>');
L.push('                    )}');
const insert = L.join(EOL);

const out = src.replace(anchorRe, anchorText + insert);
if (out === src) die('replace produced no change');
if (out.split('Abort Pending Agreement').length - 1 !== 2) die('expected button title + alert title = 2 occurrences');
if (out.split('aborted-pending').length - 1 !== 1) die('archive tag missing');
if (out.split('5f: ABORT PENDING').length - 1 !== 1) die('marker comment missing');
fs.writeFileSync(p, out, 'utf8');
console.log('[Abort] OK - 5f Abort button inserted after Reclaim, seller-gated, L1-empty safety gate.');