// AUTO-GENERATED by build_scene_engine.cjs - DO NOT EDIT BY HAND.
// Source of truth: scene_engine.html (open it in a browser to test).
// Regenerate with: node .\\build_scene_engine.cjs

/* eslint-disable */
export const SCENE_ENGINE_HTML: string = `<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
<style>
  html,body{margin:0;padding:0;background:#000;overflow:hidden;height:100%;
    -webkit-user-select:none;user-select:none;-webkit-touch-callout:none;
    font-family:-apple-system,system-ui,sans-serif}
  #view{position:absolute;inset:0;width:100%;height:100%;image-rendering:pixelated}
  #hud{position:absolute;inset:0;pointer-events:none;color:#e8e2d0;font-size:12px}
  .bar{position:absolute;border:1px solid rgba(0,0,0,.5)}
  .bar > i{display:block;height:100%}
  .lbl{position:absolute;text-shadow:1px 1px 0 #000;white-space:pre}
  #err{position:absolute;inset:0;background:#111;color:#e88;padding:16px;
    font-family:monospace;font-size:11px;white-space:pre-wrap;overflow:auto;display:none}
  .stick{position:absolute;bottom:24px;width:96px;height:96px;border-radius:50%;
    background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.15)}
  .stick > b{position:absolute;left:32px;top:32px;width:32px;height:32px;border-radius:50%;
    background:rgba(255,255,255,.25);display:block}
  .btn{position:absolute;width:58px;height:58px;border-radius:50%;
    background:rgba(255,255,255,.10);border:1px solid rgba(255,255,255,.2);
    color:#e8e2d0;font-size:13px;line-height:58px;text-align:center}
  #pad{position:absolute;inset:0;pointer-events:auto}
</style>

<canvas id="view"></canvas>
<div id="hud"></div>
<div id="pad"></div>
<div id="err"></div>

<script>
"use strict";
// ===========================================================================
// KASVILLAGE SCENE ENGINE v1  (kv_scene_v1)
// ---------------------------------------------------------------------------
// Reads a declarative scene JSON and runs it. No author code executes: the
// engine is the only logic, scenes only select and configure what it provides.
// PS1 look is reproduced by constraint, not post-processing -- low internal
// resolution, vertex snapping, affine (perspective-incorrect) texture mapping,
// painter's-algorithm depth sorting, flat shading and distance fog.
// ===========================================================================

var E = {};              // engine namespace
var scene = null;        // parsed scene
var canvas, ctx, hud, pad, W = 320, H = 240, scale = 1;
var nodes = {};          // id -> node
var actors = [];         // nodes with controllers/state machines
var drawList = [];       // faces queued each frame
var meshCache = {};      // name -> geometry
var texCache = {};       // name -> canvas
var world = { alert: false, flags: {}, score: 0, time: 0 };
var camera = null, running = false, lastT = 0, accum = 0;

// ---------------------------------------------------------------------------
// SEEDED RNG  -- every client derives identical worlds from meta.seed
// ---------------------------------------------------------------------------
function hashStr(s) {
  var h = 2166136261 >>> 0;
  for (var i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 16777619) >>> 0; }
  return h >>> 0;
}
function mulberry(seed) {
  var a = seed >>> 0;
  return function () {
    a = (a + 0x6D2B79F5) >>> 0;
    var t = a;
    t = Math.imul(t ^ (t >>> 15), 1 | t);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
var rnd = mulberry(1);
function srandFor(tag) { return mulberry(hashStr((scene.meta.seed || "kv") + ":" + tag)); }

// value noise for terrain and textures
function noise2(rng) {
  var g = [], N = 64, i;
  for (i = 0; i < N * N; i++) g.push(rng());
  return function (x, y) {
    var xi = Math.floor(x), yi = Math.floor(y), xf = x - xi, yf = y - yi;
    function at(a, b) { return g[(((b % N) + N) % N) * N + (((a % N) + N) % N)]; }
    var u = xf * xf * (3 - 2 * xf), v = yf * yf * (3 - 2 * yf);
    var a = at(xi, yi), b = at(xi + 1, yi), c = at(xi, yi + 1), d = at(xi + 1, yi + 1);
    return a * (1 - u) * (1 - v) + b * u * (1 - v) + c * (1 - u) * v + d * u * v;
  };
}

// ---------------------------------------------------------------------------
// VECTOR / MATRIX
// ---------------------------------------------------------------------------
function v3(x, y, z) { return { x: x || 0, y: y || 0, z: z || 0 }; }
function vadd(a, b) { return v3(a.x + b.x, a.y + b.y, a.z + b.z); }
function vsub(a, b) { return v3(a.x - b.x, a.y - b.y, a.z - b.z); }
function vmul(a, s) { return v3(a.x * s, a.y * s, a.z * s); }
function vlen(a) { return Math.sqrt(a.x * a.x + a.y * a.y + a.z * a.z); }
function vnorm(a) { var l = vlen(a) || 1; return vmul(a, 1 / l); }
function vcross(a, b) {
  return v3(a.y * b.z - a.z * b.y, a.z * b.x - a.x * b.z, a.x * b.y - a.y * b.x);
}
function vdot(a, b) { return a.x * b.x + a.y * b.y + a.z * b.z; }
function dist(a, b) { return vlen(vsub(a, b)); }
var DEG = Math.PI / 180;

function matIdent() { return [1,0,0,0, 0,1,0,0, 0,0,1,0, 0,0,0,1]; }
function matMul(a, b) {
  var o = new Array(16);
  for (var r = 0; r < 4; r++) for (var c = 0; c < 4; c++) {
    o[r * 4 + c] = a[r * 4] * b[c] + a[r * 4 + 1] * b[4 + c] + a[r * 4 + 2] * b[8 + c] + a[r * 4 + 3] * b[12 + c];
  }
  return o;
}
function matTrans(x, y, z) { var m = matIdent(); m[3] = x; m[7] = y; m[11] = z; return m; }
function matScale(x, y, z) { var m = matIdent(); m[0] = x; m[5] = y; m[10] = z; return m; }
function matRotX(d) { var c = Math.cos(d * DEG), s = Math.sin(d * DEG), m = matIdent(); m[5] = c; m[6] = -s; m[9] = s; m[10] = c; return m; }
function matRotY(d) { var c = Math.cos(d * DEG), s = Math.sin(d * DEG), m = matIdent(); m[0] = c; m[2] = s; m[8] = -s; m[10] = c; return m; }
function matRotZ(d) { var c = Math.cos(d * DEG), s = Math.sin(d * DEG), m = matIdent(); m[0] = c; m[1] = -s; m[4] = s; m[5] = c; return m; }
function matApply(m, p) {
  return v3(
    m[0] * p.x + m[1] * p.y + m[2] * p.z + m[3],
    m[4] * p.x + m[5] * p.y + m[6] * p.z + m[7],
    m[8] * p.x + m[9] * p.y + m[10] * p.z + m[11]
  );
}
function nodeMatrix(n) {
  var t = n.transform || {};
  var p = t.pos || [0, 0, 0], r = t.rot || [0, 0, 0], s = t.scale || [1, 1, 1];
  var m = matTrans(p[0], p[1], p[2]);
  m = matMul(m, matRotY(r[1] || 0));
  m = matMul(m, matRotX(r[0] || 0));
  m = matMul(m, matRotZ(r[2] || 0));
  return matMul(m, matScale(s[0], s[1], s[2]));
}

// ---------------------------------------------------------------------------
// PROCEDURAL TEXTURES  -- recipes, never binary assets
// ---------------------------------------------------------------------------
function makeTexture(name, spec) {
  if (texCache[name]) return texCache[name];
  var size = spec.size || 64;
  var c = document.createElement("canvas");
  c.width = size; c.height = size;
  var g = c.getContext("2d");
  var cols = spec.colors || ["#888", "#aaa"];
  var rng = srandFor("tex:" + name);
  g.fillStyle = cols[0]; g.fillRect(0, 0, size, size);

  if (spec.type === "noise") {
    var nz = noise2(rng), sc = (spec.scale || 16) / size;
    var img = g.getImageData(0, 0, size, size), d = img.data;
    var c0 = hex2rgb(cols[0]), c1 = hex2rgb(cols[1] || cols[0]);
    for (var y = 0; y < size; y++) for (var x = 0; x < size; x++) {
      var t = nz(x * sc, y * sc), i = (y * size + x) * 4;
      d[i] = c0[0] + (c1[0] - c0[0]) * t;
      d[i + 1] = c0[1] + (c1[1] - c0[1]) * t;
      d[i + 2] = c0[2] + (c1[2] - c0[2]) * t;
      d[i + 3] = 255;
    }
    g.putImageData(img, 0, 0);
  } else if (spec.type === "brick") {
    var rows = spec.rows || 6, colsN = spec.cols || 4, mor = spec.mortar || 1;
    var bh = size / rows, bw = size / colsN;
    g.fillStyle = cols[1] || "#555"; g.fillRect(0, 0, size, size);
    g.fillStyle = cols[0];
    for (var r2 = 0; r2 < rows; r2++) {
      var off = (r2 % 2) * bw / 2;
      for (var c2 = -1; c2 <= colsN; c2++) {
        g.fillRect(c2 * bw + off + mor, r2 * bh + mor, bw - mor * 2, bh - mor * 2);
      }
    }
  } else if (spec.type === "stripe") {
    var wdt = spec.width || 4;
    g.save(); g.translate(size / 2, size / 2); g.rotate((spec.angle || 45) * DEG); g.translate(-size, -size);
    for (var i2 = 0; i2 < size * 2 / wdt; i2++) {
      g.fillStyle = cols[i2 % 2] || cols[0];
      g.fillRect(i2 * wdt, 0, wdt, size * 2);
    }
    g.restore();
  } else if (spec.type === "checker") {
    var n = spec.cells || 8, cs = size / n;
    for (var yy = 0; yy < n; yy++) for (var xx = 0; xx < n; xx++) {
      g.fillStyle = cols[(xx + yy) % 2] || cols[0];
      g.fillRect(xx * cs, yy * cs, cs, cs);
    }
  }
  texCache[name] = c;
  return c;
}
function hex2rgb(h) {
  h = (h || "#888").replace("#", "");
  if (h.length === 3) h = h[0] + h[0] + h[1] + h[1] + h[2] + h[2];
  return [parseInt(h.slice(0, 2), 16), parseInt(h.slice(2, 4), 16), parseInt(h.slice(4, 6), 16)];
}

// ---------------------------------------------------------------------------
// MESH RECIPES  -- geometry is generated, never shipped
// ---------------------------------------------------------------------------
function quad(g, a, b, c, d) {
  var base = g.verts.length;
  g.verts.push(a, b, c, d);
  g.faces.push({ i: [base, base + 1, base + 2], uv: [[0,0],[1,0],[1,1]] });
  g.faces.push({ i: [base, base + 2, base + 3], uv: [[0,0],[1,1],[0,1]] });
}
function buildMesh(name, spec) {
  if (meshCache[name]) return meshCache[name];
  var g = { verts: [], faces: [] }, i, j;
  var t = spec.type;

  if (t === "plane") {
    var sz = spec.size || [20, 20], sub = spec.subdiv || 4;
    var hn = spec.heightNoise, nz = hn ? noise2(srandFor("mesh:" + name)) : null;
    var stepX = sz[0] / sub, stepZ = sz[1] / sub;
    function hAt(x, z) {
      if (!nz) return 0;
      return (nz(x * (hn.scale || 0.1), z * (hn.scale || 0.1)) - 0.5) * 2 * (hn.amp || 1);
    }
    for (i = 0; i < sub; i++) for (j = 0; j < sub; j++) {
      var x0 = -sz[0] / 2 + i * stepX, z0 = -sz[1] / 2 + j * stepZ;
      var x1 = x0 + stepX, z1 = z0 + stepZ;
      quad(g,
        v3(x0, hAt(x0, z0), z0), v3(x1, hAt(x1, z0), z0),
        v3(x1, hAt(x1, z1), z1), v3(x0, hAt(x0, z1), z1));
    }
    g.heightFn = hAt;
  } else if (t === "box") {
    var s = spec.size || [1, 1, 1];
    var hx = s[0] / 2, hy = s[1] / 2, hz = s[2] / 2, oy = spec.originBottom ? hy : 0;
    var p = [
      v3(-hx, -hy + oy, -hz), v3(hx, -hy + oy, -hz), v3(hx, hy + oy, -hz), v3(-hx, hy + oy, -hz),
      v3(-hx, -hy + oy, hz), v3(hx, -hy + oy, hz), v3(hx, hy + oy, hz), v3(-hx, hy + oy, hz)];
    quad(g, p[0], p[1], p[2], p[3]); quad(g, p[5], p[4], p[7], p[6]);
    quad(g, p[4], p[0], p[3], p[7]); quad(g, p[1], p[5], p[6], p[2]);
    quad(g, p[3], p[2], p[6], p[7]); quad(g, p[4], p[5], p[1], p[0]);
  } else if (t === "cylinder") {
    var seg = spec.segments || 8, rad = spec.radius || 1, hgt = spec.height || 2;
    for (i = 0; i < seg; i++) {
      var a0 = i / seg * Math.PI * 2, a1 = (i + 1) / seg * Math.PI * 2;
      quad(g,
        v3(Math.cos(a0) * rad, 0, Math.sin(a0) * rad), v3(Math.cos(a1) * rad, 0, Math.sin(a1) * rad),
        v3(Math.cos(a1) * rad, hgt, Math.sin(a1) * rad), v3(Math.cos(a0) * rad, hgt, Math.sin(a0) * rad));
    }
  } else if (t === "lathe") {
    var prof = spec.profile || [[0, 0], [1, 0], [1, 1]], sg = spec.segments || 8;
    for (i = 0; i < sg; i++) {
      var b0 = i / sg * Math.PI * 2, b1 = (i + 1) / sg * Math.PI * 2;
      for (j = 0; j < prof.length - 1; j++) {
        var r0 = prof[j][0], y0 = prof[j][1], r1 = prof[j + 1][0], y1 = prof[j + 1][1];
        quad(g,
          v3(Math.cos(b0) * r0, y0, Math.sin(b0) * r0), v3(Math.cos(b1) * r0, y0, Math.sin(b1) * r0),
          v3(Math.cos(b1) * r1, y1, Math.sin(b1) * r1), v3(Math.cos(b0) * r1, y1, Math.sin(b0) * r1));
      }
    }
  } else if (t === "extrude") {
    var poly = spec.polygon || [[-1,-1],[1,-1],[1,1],[-1,1]], hh = spec.height || 2;
    for (i = 0; i < poly.length; i++) {
      var q0 = poly[i], q1 = poly[(i + 1) % poly.length];
      quad(g, v3(q0[0], 0, q0[1]), v3(q1[0], 0, q1[1]), v3(q1[0], hh, q1[1]), v3(q0[0], hh, q0[1]));
    }
    if (spec.cap === "pyramid") {
      var ch = hh + (spec.capHeight || 1), cx = 0, cz = 0;
      for (i = 0; i < poly.length; i++) { cx += poly[i][0]; cz += poly[i][1]; }
      cx /= poly.length; cz /= poly.length;
      for (i = 0; i < poly.length; i++) {
        var w0 = poly[i], w1 = poly[(i + 1) % poly.length], base = g.verts.length;
        g.verts.push(v3(w0[0], hh, w0[1]), v3(w1[0], hh, w1[1]), v3(cx, ch, cz));
        g.faces.push({ i: [base, base + 1, base + 2], uv: [[0,0],[1,0],[0.5,1]] });
      }
    } else {
      var bb = g.verts.length;
      for (i = 0; i < poly.length; i++) g.verts.push(v3(poly[i][0], hh, poly[i][1]));
      for (i = 1; i < poly.length - 1; i++) {
        g.faces.push({ i: [bb, bb + i, bb + i + 1], uv: [[0,0],[1,0],[1,1]] });
      }
    }
  } else if (t === "silhouette") {
    // Low-poly figure assembled from boxes. Period-correct for the era and
    // keeps the whole character under a few dozen polygons.
    var beast = spec.generator === "beast";
    var sc = beast ? 1.5 : 1;
    function limb(cx, cy, cz, w, h, d) {
      var m = buildMesh("_tmpbox" + g.verts.length, { type: "box", size: [w, h, d] });
      var off = v3(cx, cy, cz), base2 = g.verts.length;
      for (var k = 0; k < m.verts.length; k++) g.verts.push(vadd(m.verts[k], off));
      for (var k2 = 0; k2 < m.faces.length; k2++) {
        g.faces.push({ i: [m.faces[k2].i[0] + base2, m.faces[k2].i[1] + base2, m.faces[k2].i[2] + base2], uv: m.faces[k2].uv });
      }
      delete meshCache["_tmpbox" + base2];
    }
    limb(0, 1.5 * sc, 0, 0.7 * sc, 0.9 * sc, 0.45 * sc);   // torso
    limb(0, 2.15 * sc, 0, 0.45 * sc, 0.42 * sc, 0.42 * sc); // head
    limb(-0.5 * sc, 1.5 * sc, 0, 0.25 * sc, 0.8 * sc, 0.25 * sc); // arm L
    limb(0.5 * sc, 1.5 * sc, 0, 0.25 * sc, 0.8 * sc, 0.25 * sc);  // arm R
    limb(-0.22 * sc, 0.55 * sc, 0, 0.28 * sc, 1.1 * sc, 0.28 * sc); // leg L
    limb(0.22 * sc, 0.55 * sc, 0, 0.28 * sc, 1.1 * sc, 0.28 * sc);  // leg R
    if (beast) { limb(0, 2.5 * sc, 0.2 * sc, 0.15 * sc, 0.4 * sc, 0.15 * sc); }
  } else {
    g = buildMesh("_fallback", { type: "box", size: [1, 1, 1] });
  }
  meshCache[name] = g;
  return g;
}

// ---------------------------------------------------------------------------
// EXPRESSION LANGUAGE  -- closed grammar: no calls beyond the whitelist, no
// loops, no assignment, no member invocation. Anything else fails to parse.
// ---------------------------------------------------------------------------
var FN = {
  // Accepts nodes or raw vectors. Nodes resolve through worldPos so parenting
  // and animation offsets are respected.
  distance: function (a, b) {
    if (!a || !b) return 9999;
    var pa = a.worldPos || a, pb = b.worldPos || b;
    if (pa.x === undefined || pb.x === undefined) return 9999;
    return dist(pa, pb);
  },
  length: function (a) { return typeof a === "number" ? Math.abs(a) : vlen(a || v3()); },
  min: Math.min, max: Math.max, abs: Math.abs,
  rand: function () { return rnd(); }
};
function tokenize(s) {
  var out = [], i = 0;
  var ops = ["<=", ">=", "==", "!=", "&&", "||", "<", ">", "+", "-", "*", "/", "(", ")", ",", "!", "."];
  while (i < s.length) {
    var c = s[i];
    if (c === " ") { i++; continue; }
    var matched = false;
    for (var k = 0; k < ops.length; k++) {
      if (s.substr(i, ops[k].length) === ops[k]) { out.push({ t: "op", v: ops[k] }); i += ops[k].length; matched = true; break; }
    }
    if (matched) continue;
    if (/[0-9]/.test(c)) {
      var num = "";
      while (i < s.length && /[0-9.]/.test(s[i])) num += s[i++];
      out.push({ t: "num", v: parseFloat(num) }); continue;
    }
    if (/[A-Za-z_]/.test(c)) {
      var id = "";
      while (i < s.length && /[A-Za-z0-9_]/.test(s[i])) id += s[i++];
      out.push({ t: "id", v: id }); continue;
    }
    throw new Error("bad char in expression: " + c);
  }
  return out;
}
function parseExpr(toks) {
  var p = 0, depth = 0;
  function peek() { return toks[p]; }
  function eat(v) { var t = toks[p]; if (!t || (v && t.v !== v)) throw new Error("expected " + v); p++; return t; }
  function primary() {
    if (++depth > 24) throw new Error("expression too deep");
    var t = peek();
    if (!t) throw new Error("unexpected end");
    if (t.t === "num") { p++; depth--; return { k: "num", v: t.v }; }
    if (t.v === "!") { p++; var e = primary(); depth--; return { k: "not", a: e }; }
    if (t.v === "-") { p++; var e2 = primary(); depth--; return { k: "neg", a: e2 }; }
    if (t.v === "(") { p++; var e3 = expr(); eat(")"); depth--; return e3; }
    if (t.t === "id") {
      p++;
      if (peek() && peek().v === "(") {
        if (!FN[t.v]) throw new Error("function not allowed: " + t.v);
        p++; var args = [];
        if (peek() && peek().v !== ")") {
          args.push(expr());
          while (peek() && peek().v === ",") { p++; args.push(expr()); }
        }
        eat(")"); depth--;
        return { k: "call", f: t.v, args: args };
      }
      var path = [t.v];
      while (peek() && peek().v === ".") { p++; path.push(eat().v); }
      depth--;
      return { k: "path", p: path };
    }
    throw new Error("unexpected token " + t.v);
  }
  function binL(next, opsList) {
    return function () {
      var l = next();
      while (peek() && peek().t === "op" && opsList.indexOf(peek().v) >= 0) {
        var o = eat().v; l = { k: "bin", o: o, a: l, b: next() };
      }
      return l;
    };
  }
  var mul = binL(primary, ["*", "/"]);
  var add = binL(mul, ["+", "-"]);
  var cmp = binL(add, ["<", ">", "<=", ">="]);
  var eq = binL(cmp, ["==", "!="]);
  var and = binL(eq, ["&&"]);
  var expr = binL(and, ["||"]);
  var r = expr();
  if (p < toks.length) throw new Error("trailing tokens");
  return r;
}
var exprCache = {};
function compileExpr(src) {
  if (exprCache[src]) return exprCache[src];
  var ast;
  try { ast = parseExpr(tokenize(src)); }
  catch (e) { console.warn("[expr] " + src + " :: " + e.message); ast = { k: "num", v: 0 }; }
  exprCache[src] = ast;
  return ast;
}
function resolvePath(path, ctx) {
  var cur = ctx[path[0]];
  for (var i = 1; i < path.length && cur != null; i++) {
    if (path[i] === "pos" && cur.worldPos) { cur = cur.worldPos; continue; }
    cur = cur[path[i]];
  }
  return cur;
}
function evalExpr(node, ctx) {
  switch (node.k) {
    case "num": return node.v;
    case "neg": return -evalExpr(node.a, ctx);
    case "not": return !evalExpr(node.a, ctx);
    case "path": var r = resolvePath(node.p, ctx); return r === undefined ? 0 : r;
    case "call":
      var args = node.args.map(function (a) { return evalExpr(a, ctx); });
      return FN[node.f].apply(null, args);
    case "bin":
      var a = evalExpr(node.a, ctx), b = evalExpr(node.b, ctx);
      switch (node.o) {
        case "+": return a + b; case "-": return a - b;
        case "*": return a * b; case "/": return b === 0 ? 0 : a / b;
        case "<": return a < b; case ">": return a > b;
        case "<=": return a <= b; case ">=": return a >= b;
        case "==": return a === b; case "!=": return a !== b;
        case "&&": return a && b; case "||": return a || b;
      }
  }
  return 0;
}
function exprCtx(self) {
  return {
    self: self, world: world, input: INPUT,
    player: nodes[playerId] || null,
    animation: { finished: self && self._animDone },
    session: SESSION,
    time: world.time
  };
}

// ---------------------------------------------------------------------------
// INPUT  -- named actions only; scenes never see key codes
// ---------------------------------------------------------------------------
var INPUT = {
  move: { x: 0, y: 0, length: 0 },
  look: { x: 0, y: 0, length: 0 },
  interact: { pressed: false, held: false },
  attack: { pressed: false, held: false }
};
var keys = {};
function setupInput() {
  window.addEventListener("keydown", function (e) { keys[e.key.toLowerCase()] = true; });
  window.addEventListener("keyup", function (e) { keys[e.key.toLowerCase()] = false; });

  pad.innerHTML =
    '<div class="stick" id="sL" style="left:20px"><b></b></div>' +
    '<div class="btn" id="bA" style="right:96px;bottom:40px">A</div>' +
    '<div class="btn" id="bB" style="right:24px;bottom:76px">B</div>';
  var sL = document.getElementById("sL"), knob = sL.querySelector("b");
  var touchId = null, cx = 0, cy = 0;

  function stickStart(e) {
    var t = e.changedTouches ? e.changedTouches[0] : e;
    touchId = t.identifier === undefined ? 1 : t.identifier;
    var r = sL.getBoundingClientRect(); cx = r.left + r.width / 2; cy = r.top + r.height / 2;
    e.preventDefault();
  }
  function stickMove(e) {
    if (touchId === null) return;
    var list = e.changedTouches || [e], t = null;
    for (var i = 0; i < list.length; i++) {
      if (list[i].identifier === touchId || touchId === 1) { t = list[i]; break; }
    }
    if (!t) return;
    var dx = t.clientX - cx, dy = t.clientY - cy, m = Math.sqrt(dx * dx + dy * dy), R = 40;
    if (m > R) { dx = dx / m * R; dy = dy / m * R; m = R; }
    knob.style.left = (32 + dx * 0.8) + "px"; knob.style.top = (32 + dy * 0.8) + "px";
    INPUT.move.x = dx / R; INPUT.move.y = -dy / R;
    INPUT.move.length = Math.min(1, m / R);
    e.preventDefault();
  }
  function stickEnd() {
    touchId = null; knob.style.left = "32px"; knob.style.top = "32px";
    INPUT.move.x = 0; INPUT.move.y = 0; INPUT.move.length = 0;
  }
  sL.addEventListener("touchstart", stickStart); sL.addEventListener("mousedown", stickStart);
  window.addEventListener("touchmove", stickMove, { passive: false }); window.addEventListener("mousemove", stickMove);
  window.addEventListener("touchend", stickEnd); window.addEventListener("mouseup", stickEnd);

  function bindBtn(id, act) {
    var el = document.getElementById(id);
    function dn(e) { INPUT[act].held = true; INPUT[act]._edge = true; e.preventDefault(); }
    function up(e) { INPUT[act].held = false; e.preventDefault(); }
    el.addEventListener("touchstart", dn); el.addEventListener("mousedown", dn);
    el.addEventListener("touchend", up); el.addEventListener("mouseup", up);
  }
  bindBtn("bA", "interact"); bindBtn("bB", "attack");

  // drag anywhere outside the stick = look
  var lookId = null, lx = 0, ly = 0;
  pad.addEventListener("touchstart", function (e) {
    var t = e.changedTouches[0];
    if (t.clientX < window.innerWidth * 0.4) return;
    lookId = t.identifier; lx = t.clientX; ly = t.clientY;
  });
  pad.addEventListener("touchmove", function (e) {
    for (var i = 0; i < e.changedTouches.length; i++) {
      var t = e.changedTouches[i];
      if (t.identifier !== lookId) continue;
      INPUT.look.x = (t.clientX - lx) * 0.4; INPUT.look.y = (t.clientY - ly) * 0.4;
      lx = t.clientX; ly = t.clientY;
    }
  }, { passive: false });
  pad.addEventListener("touchend", function () { lookId = null; INPUT.look.x = 0; INPUT.look.y = 0; });
}
function pollKeys() {
  var mx = 0, my = 0;
  if (keys["w"] || keys["arrowup"]) my += 1;
  if (keys["s"] || keys["arrowdown"]) my -= 1;
  if (keys["a"] || keys["arrowleft"]) mx -= 1;
  if (keys["d"] || keys["arrowright"]) mx += 1;
  if (mx || my) {
    var m = Math.sqrt(mx * mx + my * my);
    INPUT.move.x = mx / m; INPUT.move.y = my / m; INPUT.move.length = 1;
  }
  if (keys["q"]) INPUT.look.x = -3;
  if (keys["e"] && !INPUT.interact.held) { INPUT.interact.held = true; INPUT.interact._edge = true; }
  if (!keys["e"]) INPUT.interact.held = false;
  if (keys[" "] && !INPUT.attack.held) { INPUT.attack.held = true; INPUT.attack._edge = true; }
  if (!keys[" "]) INPUT.attack.held = false;
}
function edgeFlush() {
  ["interact", "attack"].forEach(function (k) {
    INPUT[k].pressed = !!INPUT[k]._edge; INPUT[k]._edge = false;
  });
}

// ---------------------------------------------------------------------------
// SCENE BUILD
// ---------------------------------------------------------------------------
var playerId = null, terrainMesh = null;

function walkNodes(list, parent) {
  (list || []).forEach(function (n) {
    n._parent = parent || null;
    n.worldPos = v3();
    nodes[n.id] = n;

    if (n.type === "Spawner") { expandSpawner(n); }
    if (n.mesh) n._geo = buildMesh(n.mesh, (scene.resources.meshes || {})[n.mesh] || { type: "box" });
    if (n.id === "terrain" || (n.collision === "mesh" && n._geo && n._geo.heightFn)) terrainMesh = n;
    if ((n.tags || []).indexOf("player") >= 0) playerId = n.id;
    if (n.type === "Camera3D") camera = n;
    if (n.stateMachine) {
      n._state = n.stateMachine.initial;
      n._stateT = 0;
      actors.push(n);
    } else if (n.controller) { actors.push(n); }
    if (n.stats) { n.hp = n.stats.hp; n.maxHp = n.stats.maxHp || n.stats.hp; }
    walkNodes(n.children, n);
  });
}

function expandSpawner(n) {
  var pl = n.placement || {}, rng = srandFor("spawn:" + n.id);
  var out = [], tries = 0;
  var inner = pl.innerRadius || 5, outer = pl.outerRadius || 20, minS = pl.minSpacing || 3;
  while (out.length < (n.count || 1) && tries < 500) {
    tries++;
    var ang = rng() * Math.PI * 2, rad = inner + rng() * (outer - inner);
    var px = Math.cos(ang) * rad, pz = Math.sin(ang) * rad, ok = true;
    for (var i = 0; i < out.length; i++) {
      var dx = out[i][0] - px, dz = out[i][2] - pz;
      if (Math.sqrt(dx * dx + dz * dz) < minS) { ok = false; break; }
    }
    if (ok) out.push([px, 0, pz]);
  }
  n.children = n.children || [];
  out.forEach(function (p, idx) {
    n.children.push({
      id: n.id + "_" + idx, type: "MeshInstance", mesh: n.mesh, material: n.material,
      transform: { pos: p, rot: [0, pl.faceCenter ? (Math.atan2(-p[0], -p[2]) / DEG) : rng() * 360, 0] }
    });
  });
  n.mesh = null;
}

function terrainHeight(x, z) {
  if (terrainMesh && terrainMesh._geo && terrainMesh._geo.heightFn) return terrainMesh._geo.heightFn(x, z);
  return 0;
}

// ---------------------------------------------------------------------------
// ACTOR UPDATE  -- controllers, state machines, behaviors
// ---------------------------------------------------------------------------
var camYaw = 0, camPitch = -10;

function updateActor(n, dt) {
  var t = n.transform = n.transform || {};
  t.pos = t.pos || [0, 0, 0];
  t.rot = t.rot || [0, 0, 0];
  var ctl = n.controller;

  if (ctl && ctl.type === "thirdPerson") {
    camYaw += INPUT.look.x * dt * 60 * 0.5;
    var sp = (n.stats && n.stats.speed) || 4;
    if (INPUT.move.length > 0.05) {
      var ang = camYaw * DEG;
      var fx = Math.sin(ang), fz = Math.cos(ang);
      var dx = (fx * INPUT.move.y + fz * INPUT.move.x) * sp * dt;
      var dz = (fz * INPUT.move.y - fx * INPUT.move.x) * sp * dt;
      t.pos[0] += dx; t.pos[2] += dz;
      t.rot[1] = Math.atan2(dx, dz) / DEG;
    }
    t.pos[1] = terrainHeight(t.pos[0], t.pos[2]);
  }

  if (ctl && ctl.type === "railPath") {
    // 2.5D rail: position is distance along a path plus a jump arc.
    var path = nodes[ctl.path];
    if (path && path.points && path.points.length > 1) {
      n._u = (n._u || 0) + INPUT.move.x * ((n.stats && n.stats.speed) || 5) * dt;
      var pt = samplePath(path, n._u);
      t.pos[0] = pt.x; t.pos[2] = pt.z;
      n._vy = (n._vy || 0);
      if (INPUT.attack.pressed && Math.abs(n._airY || 0) < 0.01) n._vy = ctl.jumpVelocity || 7;
      n._vy -= (ctl.gravity || 18) * dt;
      n._airY = Math.max(0, (n._airY || 0) + n._vy * dt);
      t.pos[1] = pt.y + n._airY;
      t.rot[1] = pt.yaw;
    }
  }

  if (n.stateMachine) updateStateMachine(n, dt);
  if (n.animations && n._anim) updateAnimation(n, dt);
}

function samplePath(path, u) {
  var pts = path.points, closed = path.closed;
  var segs = [], total = 0, i;
  for (i = 0; i < pts.length - (closed ? 0 : 1); i++) {
    var a = pts[i], b = pts[(i + 1) % pts.length];
    var d = Math.sqrt(Math.pow(b[0] - a[0], 2) + Math.pow(b[2] - a[2], 2));
    segs.push({ a: a, b: b, d: d }); total += d;
  }
  if (total <= 0) return { x: pts[0][0], y: pts[0][1], z: pts[0][2], yaw: 0 };
  var dd = ((u % total) + total) % total;
  for (i = 0; i < segs.length; i++) {
    if (dd <= segs[i].d) {
      var f = segs[i].d === 0 ? 0 : dd / segs[i].d, s = segs[i];
      return {
        x: s.a[0] + (s.b[0] - s.a[0]) * f,
        y: s.a[1] + (s.b[1] - s.a[1]) * f,
        z: s.a[2] + (s.b[2] - s.a[2]) * f,
        yaw: Math.atan2(s.b[0] - s.a[0], s.b[2] - s.a[2]) / DEG
      };
    }
    dd -= segs[i].d;
  }
  return { x: pts[0][0], y: pts[0][1], z: pts[0][2], yaw: 0 };
}

function updateStateMachine(n, dt) {
  var sm = n.stateMachine, st = sm.states[n._state];
  if (!st) return;
  n._stateT += dt;
  var ctx = exprCtx(n);

  if (st.behavior) runBehavior(n, st.behavior, dt);

  var trans = (st.transitions || []).concat(sm.anyState || []);
  for (var i = 0; i < trans.length; i++) {
    var tr = trans[i];
    if (tr.to === n._state) continue;
    if (evalExpr(compileExpr(tr.when), ctx)) { enterState(n, tr.to); break; }
  }
}
function enterState(n, name) {
  var st = n.stateMachine.states[name];
  if (!st) return;
  n._state = name; n._stateT = 0; n._animDone = false;
  if (st.animation && n.animations && n.animations[st.animation]) {
    n._anim = { name: st.animation, t: 0, def: n.animations[st.animation] };
  }
  (st.onEnter || []).forEach(function (a) { runAction(n, a); });
}
function runBehavior(n, b, dt) {
  var t = n.transform, sp = b.speed || 3;
  if (b.type === "patrol") {
    var path = nodes[b.path];
    if (!path || !path.points) return;
    n._u = (n._u || 0) + sp * dt;
    var pt = samplePath(path, n._u);
    t.pos[0] = pt.x; t.pos[2] = pt.z; t.pos[1] = terrainHeight(pt.x, pt.z);
    t.rot[1] = pt.yaw;
  } else if (b.type === "seek") {
    var tgt = nodes[b.target];
    if (!tgt) return;
    var d = vsub(tgt.worldPos, n.worldPos); d.y = 0;
    var l = vlen(d) || 1;
    t.pos[0] += d.x / l * sp * dt; t.pos[2] += d.z / l * sp * dt;
    t.pos[1] = terrainHeight(t.pos[0], t.pos[2]);
    t.rot[1] = Math.atan2(d.x, d.z) / DEG;
  } else if (b.type === "flee") {
    var tg2 = nodes[b.target];
    if (!tg2) return;
    var d2 = vsub(n.worldPos, tg2.worldPos); d2.y = 0;
    var l2 = vlen(d2) || 1;
    t.pos[0] += d2.x / l2 * sp * dt; t.pos[2] += d2.z / l2 * sp * dt;
    t.pos[1] = terrainHeight(t.pos[0], t.pos[2]);
  }
}
function updateAnimation(n, dt) {
  var a = n._anim, def = a.def;
  a.t += dt;
  if (a.t >= def.length) {
    if (def.loop) a.t = a.t % def.length;
    else { a.t = def.length; n._animDone = true; }
  }
  n._animOffset = { posY: 0, rotX: 0, rotY: 0 };
  (def.tracks || []).forEach(function (tr) {
    var keys = tr.keys || [], val = 0;
    for (var i = 0; i < keys.length - 1; i++) {
      if (a.t >= keys[i][0] && a.t <= keys[i + 1][0]) {
        var span = keys[i + 1][0] - keys[i][0] || 1;
        var f = (a.t - keys[i][0]) / span;
        val = keys[i][1] + (keys[i + 1][1] - keys[i][1]) * f;
        break;
      }
    }
    if (tr.path.indexOf("pos.y") >= 0) n._animOffset.posY = val;
    else if (tr.path.indexOf("rot.x") >= 0) n._animOffset.rotX = val;
    else if (tr.path.indexOf("rot.y") >= 0) n._animOffset.rotY = val;
  });
}

// The complete verb set. Adding a verb requires an engine change -- that
// boundary is what keeps published scenes incapable of surprising anyone.
function runAction(self, a) {
  var target = a.target === "self" ? self : nodes[a.target];
  switch (a.action) {
    case "damage": if (target) { target.hp = Math.max(0, (target.hp || 0) - (a.amount || 0)); } break;
    case "heal": if (target) { target.hp = Math.min(target.maxHp || 999, (target.hp || 0) + (a.amount || 0)); } break;
    case "show": if (target) { target.visible = true; if (a.args && a.args[0]) target.text = a.args[0]; } break;
    case "hide": if (target) target.visible = false; break;
    case "setText": if (target) target.text = (a.args && a.args[0]) || ""; break;
    case "despawn":
      if (target) { if (a.delay) setTimeout(function () { target._dead = true; }, a.delay * 1000); else target._dead = true; }
      break;
    case "teleport":
      if (target && a.args) { target.transform.pos = [a.args[0] || 0, a.args[1] || 0, a.args[2] || 0]; }
      break;
    case "addScore": world.score += (a.amount || 0); break;
    case "setState": world.flags[a.args ? a.args[0] : "f"] = a.args ? a.args[1] : true; break;
    case "commit": bridgeCommit(); break;
    case "play": break;
  }
}

// ---------------------------------------------------------------------------
// TRIGGERS  (Area3D)
// ---------------------------------------------------------------------------
function updateAreas() {
  var pl = nodes[playerId];
  if (!pl) return;
  Object.keys(nodes).forEach(function (id) {
    var n = nodes[id];
    if (n.type !== "Area3D" || !n.signals) return;
    var r = (n.shape && n.shape.radius) || 2;
    var inside = dist(n.worldPos, pl.worldPos) < r;
    if (inside && !n._in) {
      n._in = true;
      n.signals.forEach(function (s) { if (s.signal === "body_entered") runAction(n, { action: s.action, target: s.to, args: s.args }); });
    } else if (!inside && n._in) {
      n._in = false;
      n.signals.forEach(function (s) { if (s.signal === "body_exited") runAction(n, { action: s.action, target: s.to, args: s.args }); });
    }
  });
}

// ---------------------------------------------------------------------------
// RENDER  -- painter's sort, vertex snap, affine texture mapping
// ---------------------------------------------------------------------------
var viewM = matIdent(), fovScale = 1;

function buildView() {
  var mode = (scene.render && scene.render.cameraMode) || (camera && camera.mode) || "follow";
  var eye, look;
  var pl = nodes[playerId];

  if (mode === "fixed" && camera) {
    eye = camera.worldPos;
    look = pl ? pl.worldPos : v3(0, 0, 0);
  } else if (mode === "overhead" || mode === "isometric") {
    var c = pl ? pl.worldPos : v3();
    var h = mode === "isometric" ? 14 : 20;
    eye = v3(c.x + (mode === "isometric" ? 12 : 0), c.y + h, c.z + (mode === "isometric" ? 12 : 0.01));
    look = c;
  } else if (mode === "firstPerson" && pl) {
    eye = vadd(pl.worldPos, v3(0, 1.6, 0));
    var ya = (pl.transform.rot[1] || 0) * DEG;
    look = vadd(eye, v3(Math.sin(ya), 0, Math.cos(ya)));
  } else {
    var c2 = pl ? pl.worldPos : v3();
    var ya2 = camYaw * DEG, d = (camera && camera.distance) || 7, hh = (camera && camera.height) || 3.4;
    eye = v3(c2.x - Math.sin(ya2) * d, c2.y + hh, c2.z - Math.cos(ya2) * d);
    look = vadd(c2, v3(0, 1.2, 0));
  }

  var fwd = vnorm(vsub(look, eye));
  var right = vnorm(vcross(v3(0, 1, 0), fwd));
  var up = vcross(fwd, right);
  viewM = [
    right.x, right.y, right.z, -vdot(right, eye),
    up.x, up.y, up.z, -vdot(up, eye),
    fwd.x, fwd.y, fwd.z, -vdot(fwd, eye),
    0, 0, 0, 1
  ];
  var fov = (camera && camera.fov) || 55;
  fovScale = (H / 2) / Math.tan(fov / 2 * DEG);
}

function project(p) {
  var v = matApply(viewM, p);
  if (v.z < 0.15) return null;
  var snap = (scene.render && scene.render.vertexSnap) || 0;
  var x = W / 2 + v.x * fovScale / v.z;
  var y = H / 2 - v.y * fovScale / v.z;
  if (snap > 0) { x = Math.round(x * snap) / snap; y = Math.round(y * snap) / snap; }
  return { x: x, y: y, z: v.z };
}

// World transforms are resolved in their own pass BEFORE actors think, so
// distance/vision tests never read a stale position from the previous frame.
function updateTransforms(list, parentM) {
  (list || []).forEach(function (n) {
    if (n._dead || n.type === "CanvasLayer") return;
    var m = matMul(parentM, nodeMatrix(n));
    if (n._animOffset) {
      m = matMul(m, matTrans(0, n._animOffset.posY || 0, 0));
      if (n._animOffset.rotX) m = matMul(m, matRotX(n._animOffset.rotX));
      if (n._animOffset.rotY) m = matMul(m, matRotY(n._animOffset.rotY));
    }
    n._world = m;
    n.worldPos = matApply(m, v3(0, 0, 0));
    updateTransforms(n.children, m);
  });
}

function collectNode(n, parentM) {
  if (n._dead) return;
  var m = n._world || matMul(parentM, nodeMatrix(n));

  if (n._geo && n.visible !== false) {
    var mat = (scene.resources.materials || {})[n.material] || {};
    var tex = mat.texture ? makeTexture(mat.texture, (scene.resources.textures || {})[mat.texture] || {}) : null;
    var col = mat.color || "#9a9a9a";
    var g = n._geo;
    for (var f = 0; f < g.faces.length; f++) {
      var face = g.faces[f];
      var w0 = matApply(m, g.verts[face.i[0]]);
      var w1 = matApply(m, g.verts[face.i[1]]);
      var w2 = matApply(m, g.verts[face.i[2]]);
      var p0 = project(w0), p1 = project(w1), p2 = project(w2);
      if (!p0 || !p1 || !p2) continue;
      // backface / offscreen reject
      var area = (p1.x - p0.x) * (p2.y - p0.y) - (p2.x - p0.x) * (p1.y - p0.y);
      if (area <= 0) continue;
      if (Math.max(p0.x, p1.x, p2.x) < 0 || Math.min(p0.x, p1.x, p2.x) > W) continue;
      if (Math.max(p0.y, p1.y, p2.y) < 0 || Math.min(p0.y, p1.y, p2.y) > H) continue;
      var nrm = vnorm(vcross(vsub(w1, w0), vsub(w2, w0)));
      var shade = 0.45 + 0.55 * Math.max(0, vdot(nrm, LIGHT));
      drawList.push({
        p: [p0, p1, p2], uv: face.uv, tex: tex, col: col, shade: shade,
        z: (p0.z + p1.z + p2.z) / 3, tiling: mat.tiling
      });
    }
  }
  (n.children || []).forEach(function (c) { collectNode(c, m); });
}

var LIGHT = vnorm(v3(-0.4, 0.8, -0.3));

function drawTexTri(t) {
  var p = t.p, img = t.tex, tw = img.width, th = img.height;
  var tl = t.tiling || [1, 1];
  var u0 = t.uv[0][0] * tw * tl[0], v0 = t.uv[0][1] * th * tl[1];
  var u1 = t.uv[1][0] * tw * tl[0], v1 = t.uv[1][1] * th * tl[1];
  var u2 = t.uv[2][0] * tw * tl[0], v2 = t.uv[2][1] * th * tl[1];
  var den = u0 * (v2 - v1) - u1 * v2 + u2 * v1 + (u1 - u2) * v0;
  if (den === 0) return;
  var a = -(v0 * (p[2].x - p[1].x) - v1 * p[2].x + v2 * p[1].x + (v1 - v2) * p[0].x) / den;
  var b = (v1 * p[2].y + v0 * (p[1].y - p[2].y) - v2 * p[1].y + (v2 - v1) * p[0].y) / den;
  var c = (u0 * (p[2].x - p[1].x) - u1 * p[2].x + u2 * p[1].x + (u1 - u2) * p[0].x) / den;
  var d = -(u1 * p[2].y + u0 * (p[1].y - p[2].y) - u2 * p[1].y + (u2 - u1) * p[0].y) / den;
  var e = (u0 * (v2 * p[1].x - v1 * p[2].x) + v0 * (u1 * p[2].x - u2 * p[1].x) + (u2 * v1 - u1 * v2) * p[0].x) / den;
  var fq = (u0 * (v2 * p[1].y - v1 * p[2].y) + v0 * (u1 * p[2].y - u2 * p[1].y) + (u2 * v1 - u1 * v2) * p[0].y) / den;
  ctx.save();
  ctx.beginPath();
  ctx.moveTo(p[0].x, p[0].y); ctx.lineTo(p[1].x, p[1].y); ctx.lineTo(p[2].x, p[2].y);
  ctx.closePath(); ctx.clip();
  ctx.transform(a, b, c, d, e, fq);
  ctx.drawImage(img, 0, 0);
  ctx.restore();
}

function renderFrame() {
  var r = scene.render || {};
  ctx.fillStyle = (r.fog && r.fog.color) || "#101820";
  ctx.fillRect(0, 0, W, H);

  drawList.length = 0;
  (scene.nodes || []).forEach(function (n) {
    if (n.type === "CanvasLayer") return;
    collectNode(n, matIdent());
  });
  drawList.sort(function (a, b) { return b.z - a.z; });

  var affine = r.affineTextures !== false;
  for (var i = 0; i < drawList.length; i++) {
    var t = drawList[i], p = t.p;
    if (t.tex && affine) {
      drawTexTri(t);
      // flat-shade overlay: darkening pass keeps the era's banded look
      ctx.globalAlpha = Math.max(0, 1 - t.shade);
      ctx.fillStyle = "#000";
      ctx.beginPath(); ctx.moveTo(p[0].x, p[0].y); ctx.lineTo(p[1].x, p[1].y); ctx.lineTo(p[2].x, p[2].y);
      ctx.closePath(); ctx.fill();
      ctx.globalAlpha = 1;
    } else {
      var rgb = hex2rgb(t.col);
      ctx.fillStyle = "rgb(" + Math.round(rgb[0] * t.shade) + "," + Math.round(rgb[1] * t.shade) + "," + Math.round(rgb[2] * t.shade) + ")";
      ctx.beginPath(); ctx.moveTo(p[0].x, p[0].y); ctx.lineTo(p[1].x, p[1].y); ctx.lineTo(p[2].x, p[2].y);
      ctx.closePath(); ctx.fill();
    }
    // distance fog
    if (r.fog && r.fog.enabled) {
      var near = r.fog.near || 10, far = r.fog.far || 40;
      var fa = Math.min(1, Math.max(0, (t.z - near) / (far - near)));
      if (fa > 0.01) {
        ctx.globalAlpha = fa; ctx.fillStyle = r.fog.color || "#101820";
        ctx.beginPath(); ctx.moveTo(p[0].x, p[0].y); ctx.lineTo(p[1].x, p[1].y); ctx.lineTo(p[2].x, p[2].y);
        ctx.closePath(); ctx.fill(); ctx.globalAlpha = 1;
      }
    }
  }
}

// ---------------------------------------------------------------------------
// HUD  (CanvasLayer nodes render as DOM, kept out of the rasterizer)
// ---------------------------------------------------------------------------
function buildHud() {
  hud.innerHTML = "";
  (scene.nodes || []).forEach(function (layer) {
    if (layer.type !== "CanvasLayer") return;
    (layer.children || []).forEach(function (n) {
      nodes[n.id] = n;
      var el = document.createElement("div");
      el.id = "h_" + n.id;
      if (n.type === "ProgressBar") {
        el.className = "bar";
        el.style.width = (n.size ? n.size[0] : 100) + "px";
        el.style.height = (n.size ? n.size[1] : 8) + "px";
        el.innerHTML = '<i style="background:' + (n.color || "#c33") + ';width:100%"></i>';
      } else {
        el.className = "lbl";
        el.style.fontSize = (n.size || 12) + "px";
      }
      placeAnchor(el, n);
      hud.appendChild(el);
      n._el = el;
    });
  });
}
function placeAnchor(el, n) {
  var a = n.anchor || "topLeft", p = n.pos || [0, 0];
  el.style.position = "absolute";
  if (a.indexOf("top") === 0) el.style.top = p[1] + "px";
  if (a.indexOf("bottom") === 0) el.style.bottom = (-p[1]) + "px";
  if (a.indexOf("Left") > 0) el.style.left = p[0] + "px";
  if (a.indexOf("Right") > 0) el.style.right = (-p[0]) + "px";
  if (a.indexOf("Center") > 0) { el.style.left = "50%"; el.style.transform = "translateX(-50%)"; }
}
function updateHud() {
  Object.keys(nodes).forEach(function (id) {
    var n = nodes[id];
    if (!n._el) return;
    if (n.type === "ProgressBar" && n.bind) {
      var cur = resolvePath(n.bind.split("."), exprCtx(null));
      var mx = typeof n.max === "string" ? resolvePath(n.max.split("."), exprCtx(null)) : (n.max || 100);
      var pct = Math.max(0, Math.min(1, (cur || 0) / (mx || 1)));
      n._el.firstChild.style.width = (pct * 100) + "%";
    } else if (n.type === "Label") {
      n._el.style.display = n.visible === false ? "none" : "block";
      n._el.textContent = n.text || "";
    }
  });
}

// ---------------------------------------------------------------------------
// SDK BRIDGE  -- the only channel out of the sandbox.
// ---------------------------------------------------------------------------
// The KasVillage SDK itself stays on the native side; the engine holds a thin
// proxy that forwards requests over postMessage and awaits a reply. Three rules
// keep a published scene from doing anything its author should not be able to:
//
//   1. READ-ONLY SURFACE. Nothing fund-moving is reachable. No FROST proposals,
//      no partial signatures, no release txs, no Arweave uploads, no sends. A
//      scene can learn who is playing and what their reputation is; it can
//      never move value or sign anything.
//   2. PERMISSION GATED. The scene declares scene.permissions up front, the
//      native side enforces it, and the player is told what was requested.
//      Undeclared calls are refused by the engine before they even leave.
//   3. NO DIRECT ACCESS. Scene JSON has no verb that calls the SDK. Only the
//      engine invokes it, from node types whose behaviour is fixed here.
// ---------------------------------------------------------------------------

function post(msg) {
  try {
    if (window.ReactNativeWebView) window.ReactNativeWebView.postMessage(JSON.stringify(msg));
  } catch (e) {}
}

// Everything the bridge will ever forward. Adding a method requires an engine
// change AND a native handler -- two deliberate edits, never a scene edit.
var SDK_METHODS = {
  connect: "identity",        // -> { pubkey, alias, verified }
  getUserStats: "stats",      // -> { xp, reputation, completed, deadlocked }
  getBalance: "balance",      // -> { sompi } (declared explicitly, off by default)
  getState: "persist",        // -> saved state for this gameId
  setState: "persist",        // stage state locally
  commitState: "persist"      // persist through the SDK
};

var KV = (function () {
  var pending = {}, nextId = 1, grants = {};

  function call(method, params) {
    return new Promise(function (resolve) {
      var need = SDK_METHODS[method];
      if (!need) { resolve({ error: "method not available: " + method }); return; }
      if (!grants[need]) { resolve({ error: "permission not granted: " + need }); return; }
      var id = nextId++;
      var timer = setTimeout(function () {
        if (pending[id]) { delete pending[id]; resolve({ error: "sdk timeout" }); }
      }, 8000);
      pending[id] = function (res) { clearTimeout(timer); resolve(res); };
      post({ kv: "sdk", id: id, method: method, params: params || {} });
    });
  }

  return {
    setGrants: function (list) {
      grants = {};
      (list || []).forEach(function (g) { grants[g] = true; });
      grants.persist = true; // persistence is always allowed; it is the game's own save
    },
    resolve: function (id, res) { if (pending[id]) { pending[id](res); delete pending[id]; } },
    connect: function () { return call("connect"); },
    getUserStats: function () { return call("getUserStats"); },
    getBalance: function () { return call("getBalance"); },
    getState: function (gameId) { return call("getState", { gameId: gameId }); },
    commit: function (gameId, state) { return call("commitState", { gameId: gameId, state: state }); }
  };
})();

// Identity and stats are pulled once at load and exposed to expressions as
// read-only context, so scenes can gate content on reputation without ever
// issuing a call themselves.
var SESSION = { pubkey: "", alias: "", verified: false, xp: 0, reputation: 0, balance: 0 };

function initSession() {
  var perms = (scene.permissions || []);
  KV.setGrants(perms);
  if (perms.indexOf("identity") >= 0) {
    KV.connect().then(function (r) {
      if (r && !r.error) {
        SESSION.pubkey = r.pubkey || ""; SESSION.alias = r.alias || "";
        SESSION.verified = !!r.verified;
      }
    });
  }
  if (perms.indexOf("stats") >= 0) {
    KV.getUserStats().then(function (r) {
      if (r && !r.error) { SESSION.xp = r.xp || 0; SESSION.reputation = r.reputation || 0; }
    });
  }
  if (perms.indexOf("balance") >= 0) {
    KV.getBalance().then(function (r) { if (r && !r.error) SESSION.balance = r.sompi || 0; });
  }
  if (scene.persistence && scene.persistence.restore !== false) {
    KV.getState(gameIdOf()).then(function (r) {
      if (r && !r.error && r.state) applySavedState(r.state);
    });
  }
}
function gameIdOf() {
  return (scene.persistence && scene.persistence.gameId) || scene.meta.id;
}
function applySavedState(state) {
  Object.keys(state || {}).forEach(function (k) {
    var parts = k.split("."), tgt = nodes[parts[0]];
    if (!tgt || parts.length < 2) {
      if (parts[0] === "score") world.score = state[k];
      else if (parts[0] === "flags") world.flags = state[k] || {};
      return;
    }
    var val = state[k];
    if (parts[1] === "pos" && Array.isArray(val)) { tgt.transform = tgt.transform || {}; tgt.transform.pos = val.slice(); }
    else tgt[parts[1]] = val;
  });
  console.log("[SceneEngine] restored saved state");
}
function bridgeCommit() {
  var keys2 = (scene.persistence && scene.persistence.saveKeys) || [];
  var state = {};
  keys2.forEach(function (k) {
    var v = resolvePath(k.split("."), exprCtx(null));
    if (v && v.x !== undefined) v = [v.x, v.y, v.z];
    state[k] = v;
  });
  KV.commit(gameIdOf(), state);
}

// ---------------------------------------------------------------------------
// VALIDATION  -- schema check replaces code scanning entirely
// ---------------------------------------------------------------------------
function validate(s) {
  if (!s || typeof s !== "object") return "scene is not an object";
  if (s.engine !== "scene") return "engine must be 'scene'";
  if (!s.meta || !s.meta.id) return "meta.id required";
  if (!Array.isArray(s.nodes)) return "nodes[] required";
  var lim = s.compliance || {};
  var count = 0;
  (function walk(list) {
    (list || []).forEach(function (n) { count++; walk(n.children); });
  })(s.nodes);
  if (count > (lim.maxNodes || 512)) return "too many nodes: " + count;
  // Key-level check only: a scene may *mention* these words in documentation,
  // but must never carry them as keys, which is what would smuggle behaviour.
  var forbidden = ["script", "eval", "fetch", "url", "endpoint", "html", "src", "onload", "href"];
  var bad = null;
  (function keys(o, depth) {
    if (bad || !o || typeof o !== "object" || depth > 16) return;
    if (Array.isArray(o)) { o.forEach(function (x) { keys(x, depth + 1); }); return; }
    Object.keys(o).forEach(function (k) {
      if (forbidden.indexOf(k.toLowerCase()) >= 0) { bad = k; return; }
      keys(o[k], depth + 1);
    });
  })(s, 0);
  if (bad) return "forbidden key: " + bad;
  var known = ["identity", "stats", "balance", "persist"];
  var perms = s.permissions || [];
  if (!Array.isArray(perms)) return "permissions must be an array";
  for (var pi = 0; pi < perms.length; pi++) {
    if (known.indexOf(perms[pi]) < 0) return "unknown permission: " + perms[pi];
  }
  return null;
}

// ---------------------------------------------------------------------------
// BOOT / LOOP
// ---------------------------------------------------------------------------
function resize() {
  var r = scene && scene.render ? scene.render : {};
  W = r.internalWidth || 320; H = r.internalHeight || 240;
  canvas.width = W; canvas.height = H;
  ctx = canvas.getContext("2d");
  ctx.imageSmoothingEnabled = false;
}

function loadScene(json) {
  try {
    scene = typeof json === "string" ? JSON.parse(json) : json;
  } catch (e) { return fail("scene JSON parse error: " + e.message); }
  var v = validate(scene);
  if (v) return fail("scene rejected: " + v);

  nodes = {}; actors = []; meshCache = {}; texCache = {};
  playerId = null; camera = null; terrainMesh = null;
  world = { alert: false, flags: {}, score: 0, time: 0 };
  rnd = mulberry(hashStr(scene.meta.seed || "kv"));

  scene.resources = scene.resources || {};
  resize();
  walkNodes(scene.nodes, null);
  actors.forEach(function (a) { if (a.stateMachine) enterState(a, a.stateMachine.initial); });
  buildHud();
  updateTransforms(scene.nodes, matIdent());
  initSession();
  post({ kv: "ready", id: scene.meta.id, permissions: scene.permissions || [] });
  running = true;
  lastT = performance.now();
  requestAnimationFrame(loop);
}

function fail(msg) {
  running = false;
  var el = document.getElementById("err");
  el.style.display = "block";
  el.textContent = msg;
  post({ kv: "error", message: msg });
}

function loop(t) {
  if (!running) return;
  // Clamp both ends: negative deltas (clock skew, tab restore) would otherwise
  // run the whole simulation backwards, and long stalls would tunnel actors.
  var dt = Math.max(0, Math.min(0.05, (t - lastT) / 1000));
  lastT = t;
  world.time += dt;

  INPUT.move.x = 0; INPUT.move.y = 0; INPUT.move.length = 0;
  pollKeys();
  edgeFlush();

  updateTransforms(scene.nodes, matIdent());
  actors.forEach(function (a) { if (!a._dead) updateActor(a, dt); });
  updateTransforms(scene.nodes, matIdent());
  buildView();
  updateAreas();
  renderFrame();
  updateHud();

  requestAnimationFrame(loop);
}

// entry
canvas = document.getElementById("view");
hud = document.getElementById("hud");
pad = document.getElementById("pad");
ctx = canvas.getContext("2d");
setupInput();

window.addEventListener("message", function (e) {
  try {
    var m = JSON.parse(e.data);
    if (m.kv === "load") loadScene(m.scene);
    else if (m.kv === "sdkResult") KV.resolve(m.id, m.result);
  } catch (err) {}
});
document.addEventListener("message", function (e) {
  try {
    var m = JSON.parse(e.data);
    if (m.kv === "load") loadScene(m.scene);
    else if (m.kv === "sdkResult") KV.resolve(m.id, m.result);
  } catch (err) {}
});

if (window.__KV_SCENE__) loadScene(window.__KV_SCENE__);
</script>
`;
