const fs=require('fs');let q=fs.readFileSync('QRPayNearby.tsx','utf8');
// state for showing a signed item QR
q=q.replace("const [storeLocation, setStoreLocation] = useState('');","const [storeLocation, setStoreLocation] = useState('');\n  const [itemQR, setItemQR] = useState<{ name: string; data: string } | null>(null);");
// add "Show QR" button per catalog item (in catalog list row, before Delete)
q=q.replace("<TouchableOpacity onPress={() => saveCatalog(catalog.filter(c => c.id !== item.id))}><Text style={{ color: '#FF6B6B', fontSize: rs(14) }}>Delete</Text></TouchableOpacity>","<TouchableOpacity onPress={async () => { const s = await signItem(item.id, item.name, item.priceKas); if (!s) { Alert.alert('Error', 'Could not sign item'); return; } setItemQR({ name: item.name, data: JSON.stringify({ type: 'kv_item', id: item.id, name: item.name, priceKas: item.priceKas, sig: s.sig, pubkey: s.pubkey }) }); }}><Text style={{ color: '#49d6aa', fontSize: rs(13), marginRight: rs(10) }}>Show QR</Text></TouchableOpacity>\n                  <TouchableOpacity onPress={() => saveCatalog(catalog.filter(c => c.id !== item.id))}><Text style={{ color: '#FF6B6B', fontSize: rs(14) }}>Delete</Text></TouchableOpacity>");
// item QR modal — insert right after catalog screen opening View
q=q.replace("<Text style={{ color: '#49d6aa', fontSize: rs(18), fontWeight: '700', marginBottom: rs(12) }}>Store Setup</Text>","{itemQR && (<View style={{ position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.9)', zIndex: 999, alignItems: 'center', justifyContent: 'center' }}><View style={{ backgroundColor: '#1A1A2E', borderRadius: rs(16), padding: rs(20), alignItems: 'center' }}><Text style={{ color: '#FFF', fontSize: rs(16), fontWeight: '700', marginBottom: rs(12) }}>{itemQR.name}</Text><View style={{ backgroundColor: '#FFF', padding: rs(12), borderRadius: rs(10) }}><QRCode value={itemQR.data} size={rs(200)} /></View><Text style={{ color: '#87CEEB', fontSize: rs(10), marginTop: rs(10), textAlign: 'center' }}>Print + place on item. Signed \u2014 tamper-proof.</Text><TouchableOpacity onPress={() => setItemQR(null)} style={{ marginTop: rs(14), backgroundColor: '#49d6aa', borderRadius: rs(10), padding: rs(12), paddingHorizontal: rs(30) }}><Text style={{ color: '#000', fontWeight: '700' }}>Close</Text></TouchableOpacity></View></View>)}\n            <Text style={{ color: '#49d6aa', fontSize: rs(18), fontWeight: '700', marginBottom: rs(12) }}>Store Setup</Text>");
// scanner verification — reject forged item tags
q=q.replace("if (parsed.type === 'kv_item' && parsed.id) {\n                        addToCart({ id: parsed.id, name: parsed.name, priceKas: parsed.priceKas });","if (parsed.type === 'kv_item' && parsed.id) {\n                        if (!parsed.sig || !parsed.pubkey || !verifyItem(parsed.id, parsed.name, parsed.priceKas, parsed.sig, parsed.pubkey)) { console.warn('[Shop] Rejected unsigned/forged item:', parsed.id); return; }\n                        addToCart({ id: parsed.id, name: parsed.name, priceKas: parsed.priceKas });");
fs.writeFileSync('QRPayNearby.tsx',q);console.log('done');
