const{secp256k1,schnorr}=require("@noble/curves/secp256k1");
const{sha256}=require("@noble/hashes/sha256");
const{bytesToHex,hexToBytes}=require("@noble/hashes/utils");
const N=secp256k1.CURVE.n;
const G=secp256k1.ProjectivePoint.BASE;
const B="041149b90ad3189ce363bf1b3854a4c2a2067e503b1f5d53c69d17732cb20c33";
const S="3e4bf0e0bfc642b3f0645ceaf60e1e79bac5e56d2b5597220999393b53fc6efe";
const bPub=bytesToHex(secp256k1.getPublicKey(hexToBytes(B),true));
const sPub=bytesToHex(secp256k1.getPublicKey(hexToBytes(S),true));
console.log("Buyer: sk*G ==",bPub);
console.log("Seller: sk*G ==",sPub);
var P1=secp256k1.ProjectivePoint.fromHex(bPub);
var P2=secp256k1.ProjectivePoint.fromHex(sPub);
var sk1P=G.multiply(BigInt("0x"+B));
var sk2P=G.multiply(BigInt("0x"+S));
console.log("Buyer sk*G direct:",bytesToHex(sk1P.toRawBytes(true)));
console.log("Buyer fromHex:    ",bytesToHex(P1.toRawBytes(true)));
console.log("Match:",bytesToHex(sk1P.toRawBytes(true))===bytesToHex(P1.toRawBytes(true))?"YES":"NO");
console.log("");
var[pk1,pk2]=[bPub,sPub].sort();
console.log("pk1 (sorted):",pk1.slice(0,10),"is",pk1===bPub?"BUYER":"SELLER");
console.log("pk2 (sorted):",pk2.slice(0,10),"is",pk2===bPub?"BUYER":"SELLER");
var L=sha256(hexToBytes(pk1+pk2));
var a1=BigInt("0x"+bytesToHex(sha256(new Uint8Array([...L,...hexToBytes(pk1)]))))%N;
var a2=BigInt("0x"+bytesToHex(sha256(new Uint8Array([...L,...hexToBytes(pk2)]))))%N;
console.log("a1:",a1.toString(16).slice(0,16));
console.log("a2:",a2.toString(16).slice(0,16));
console.log("");
console.log("=== Verify a_i * sk_i * G == a_i * P_i ===");
var PP1=secp256k1.ProjectivePoint.fromHex(pk1);
var PP2=secp256k1.ProjectivePoint.fromHex(pk2);
var sk_for_pk1=pk1===bPub?BigInt("0x"+B):BigInt("0x"+S);
var sk_for_pk2=pk2===bPub?BigInt("0x"+B):BigInt("0x"+S);
var left1=G.multiply((sk_for_pk1*a1)%N);
var right1=PP1.multiply(a1);
console.log("a1*sk1*G:",bytesToHex(left1.toRawBytes(true)).slice(0,20));
console.log("a1*P1:   ",bytesToHex(right1.toRawBytes(true)).slice(0,20));
console.log("Match1:",bytesToHex(left1.toRawBytes(true))===bytesToHex(right1.toRawBytes(true))?"YES":"NO");
var left2=G.multiply((sk_for_pk2*a2)%N);
var right2=PP2.multiply(a2);
console.log("a2*sk2*G:",bytesToHex(left2.toRawBytes(true)).slice(0,20));
console.log("a2*P2:   ",bytesToHex(right2.toRawBytes(true)).slice(0,20));
console.log("Match2:",bytesToHex(left2.toRawBytes(true))===bytesToHex(right2.toRawBytes(true))?"YES":"NO");
console.log("");
var Pagg=right1.add(right2);
var dAgg=((sk_for_pk1*a1)%N+(sk_for_pk2*a2)%N)%N;
var dAggP=G.multiply(dAgg);
console.log("P_agg:  ",bytesToHex(Pagg.toRawBytes(true)).slice(0,20));
console.log("dAgg*G: ",bytesToHex(dAggP.toRawBytes(true)).slice(0,20));
console.log("FINAL MATCH:",bytesToHex(Pagg.toRawBytes(true))===bytesToHex(dAggP.toRawBytes(true))?"YES":"NO");
if(bytesToHex(Pagg.toRawBytes(true))===bytesToHex(dAggP.toRawBytes(true))){
  var aggX=bytesToHex(Pagg.toRawBytes(true)).slice(2);
  var dHex=dAgg.toString(16).padStart(64,"0");
  var msg=hexToBytes("deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef");
  var sig=schnorr.sign(msg,dHex);
  console.log("schnorr.verify:",schnorr.verify(sig,msg,aggX)?"VALID !!!":"INVALID");
}
