// wire_card_trust.cjs - trust stats on the Games card.
//
// Card now shows: pledge (KAS parked in the game's chunk UTXOs, from the
// quad's pledge_kas), the dev's TownHall XP (looked up by the announce's
// signing pubkey), and a TOFU warning - the first publisher key seen for a
// game name is pinned on-device, and any later announce under that name from
// a DIFFERENT key renders a red DIFFERENT PUBLISHER banner + red button.
// Run from layer1 root:  node src\\wire_card_trust.cjs
const fs = require("fs");
const P = "VillageMailbox.tsx";
let s = fs.readFileSync(P, "utf8");
const CRLF = s.includes("\r\n");
if (CRLF) s = s.replace(/\r\n/g, "\n");
if (s.includes("kv_pub_tofu")) { console.log("already patched"); process.exit(0); }
function rep(name, a, b) {
  const f = s.split(a).length - 1;
  if (f !== 1) { console.error("ABORT [" + name + "]: found " + f + ", expected 1"); process.exit(1); }
  s = s.split(a).join(b); console.log("ok  [" + name + "]");
}
rep("trust-card", "function GameRegistryCard({ item, onInstall, installing }: any) {\n  return (\n    <View style={cardStyles.storefrontCard}>\n      <Text style={{ fontSize: 22 }}>\ud83d\udd79\ufe0f</Text>\n      <Text style={{ fontWeight: '700', marginTop: 4 }} numberOfLines={1}>{item.name}</Text>\n      <Text style={{ color: '#666', fontSize: 11 }} numberOfLines={1}>{item.category || 'Game'} \u00b7 on-chain \u00b7 verified by hash</Text>\n      <TouchableOpacity onPress={() => onInstall(item)} disabled={!!installing}\n        style={{ marginTop: 8, backgroundColor: installing ? '#999' : '#7c3aed', borderRadius: 8, paddingVertical: 6, alignItems: 'center' }}>\n        <Text style={{ color: '#fff', fontWeight: '700', fontSize: 12 }}>{installing ? 'DOWNLOADING\u2026' : 'DOWNLOAD'}</Text>\n      </TouchableOpacity>\n    </View>\n  );\n}\n", "function GameRegistryCard({ item, onInstall, installing }: any) {\n  const R = require('react');\n  const [xp, setXp] = R.useState(null as number | null);\n  R.useEffect(() => {\n    let alive = true;\n    (async () => {\n      try {\n        const tc = require('./townhall_client');\n        const f = tc.getUserStats || tc.fetchUserStats || tc.getStats;\n        if (!f || !item.o) return;\n        const st = await f(item.o);\n        if (alive && st && typeof st.xp === 'number') setXp(st.xp);\n      } catch {}\n    })();\n    return () => { alive = false; };\n  }, [item.o]);\n  const pledge = item.quad && typeof item.quad.pledge_kas === 'number' ? item.quad.pledge_kas : null;\n  return (\n    <View style={cardStyles.storefrontCard}>\n      <Text style={{ fontSize: 22 }}>\ud83d\udd79\ufe0f</Text>\n      <Text style={{ fontWeight: '700', marginTop: 4 }} numberOfLines={1}>{item.name}</Text>\n      <Text style={{ color: '#666', fontSize: 11 }} numberOfLines={1}>{item.category || 'Game'} \u00b7 on-chain \u00b7 verified by hash</Text>\n      <Text style={{ color: '#7c3aed', fontSize: 11, marginTop: 2 }} numberOfLines={1}>\n        {'\u26d3 ' + (pledge != null ? pledge + ' KAS pledged' : 'pledge n/a') + ' \u00b7 dev XP ' + (xp != null ? xp : '\u2026')}\n      </Text>\n      {item.warn ? (\n        <Text style={{ color: '#dc2626', fontSize: 10, fontWeight: '700', marginTop: 2 }}>\u26a0 DIFFERENT PUBLISHER than first seen</Text>\n      ) : null}\n      <TouchableOpacity onPress={() => onInstall(item)} disabled={!!installing}\n        style={{ marginTop: 8, backgroundColor: installing ? '#999' : (item.warn ? '#b91c1c' : '#7c3aed'), borderRadius: 8, paddingVertical: 6, alignItems: 'center' }}>\n        <Text style={{ color: '#fff', fontWeight: '700', fontSize: 12 }}>{installing ? 'DOWNLOADING\u2026' : 'DOWNLOAD'}</Text>\n      </TouchableOpacity>\n    </View>\n  );\n}\n");
rep("tofu-pin", "          const items = Array.from(byHead.values()).sort((a, b) => b.t - a.t);", "          const items = Array.from(byHead.values()).sort((a, b) => b.t - a.t);\n          // TOFU publisher pinning: the FIRST signer seen for a name is\n          // pinned on-device; a later announce under the same name from a\n          // different key gets a loud warning on its card.\n          try {\n            const tofuRaw = await AS.getItem('kv_pub_tofu');\n            const tofu = tofuRaw ? JSON.parse(tofuRaw) : {};\n            let dirty = false;\n            for (const it of items) {\n              const nm = String(it.name || '').toLowerCase();\n              if (!nm || !it.o) continue;\n              if (tofu[nm] && tofu[nm] !== it.o) (it as any).warn = true;\n              else if (!tofu[nm]) { tofu[nm] = it.o; dirty = true; }\n            }\n            if (dirty) await AS.setItem('kv_pub_tofu', JSON.stringify(tofu));\n          } catch {}");
fs.writeFileSync(P, CRLF ? s.replace(/\n/g, "\r\n") : s);
console.log("\npatched " + P + " (2 edits). Cards show pledge / dev XP / TOFU warning.");
