// wire_kv_pay.cjs - KV PAY: the one sanctioned payment surface.
//
// OnChainPageView is the single renderer for every on-chain website, store,
// dapp and game, so this one patch gives all of them an enforced native pay
// sheet. Pages request payment with an ordinary link:
//     <a href="kv://pay/<kaspa address>/<amount KAS>?m=Tip%20the%20dev">
// The sheet (system UI, outside the page sandbox) shows amount + recipient +
// the learned rule, sends via sendKaspaViaRest on CONFIRM, and fires a
// "kvpay" CustomEvent back into the page so games can react to the receipt.
// Caps: 5000 KAS per request; address prefix + length validated.
// Run from layer1 root:  node src\\wire_kv_pay.cjs
const fs = require("fs");
const P = "OnChainPageView.tsx";
let s = fs.readFileSync(P, "utf8");
const CRLF = s.includes("\r\n");
if (CRLF) s = s.replace(/\r\n/g, "\n");
if (s.includes("KV PAY")) { console.log("already patched"); process.exit(0); }
function rep(name, a, b) {
  const f = s.split(a).length - 1;
  if (f !== 1) { console.error("ABORT [" + name + "]: found " + f + ", expected 1"); process.exit(1); }
  s = s.split(a).join(b); console.log("ok  [" + name + "]");
}
rep("pay-state", "  const webRef = useRef<any>(null);", "  const webRef = useRef<any>(null);\n  const [paySheet, setPaySheet] = useState<any>(null);\n  const [payBusy, setPayBusy] = useState(false);\n  const [payDone, setPayDone] = useState<string | null>(null);");
rep("pay-link-and-confirm", "    setNotice('Unsupported link: ' + href.slice(0, 40));\n  }, [ownerPubkey, props]);", "    if (path.startsWith('pay/')) {\n      // KV PAY - the ONE sanctioned payment surface for every on-chain page,\n      // dapp and game. Format: kv://pay/<kaspa address>/<amount KAS>[?m=memo]\n      // Convention users learn: KAS only ever moves through this sheet.\n      try {\n        const rest = path.slice(4);\n        const q = rest.indexOf('?');\n        const core = q >= 0 ? rest.slice(0, q) : rest;\n        const qs = q >= 0 ? rest.slice(q + 1) : '';\n        const segs = core.split('/');\n        const addr = decodeURIComponent(segs[0] || '');\n        const kas = Number(segs[1] || '0');\n        const memo = qs.startsWith('m=') ? decodeURIComponent(qs.slice(2)).slice(0, 60) : '';\n        const okAddr = (addr.startsWith('kaspatest:') || addr.startsWith('kaspa:')) && addr.length >= 20 && addr.length <= 80;\n        if (!okAddr || !(kas > 0) || kas > 5000) { setNotice('Invalid payment request.'); return; }\n        setPayDone(null);\n        setPaySheet({ addr, kas, memo });\n      } catch { setNotice('Invalid payment request.'); }\n      return;\n    }\n    setNotice('Unsupported link: ' + href.slice(0, 40));\n  }, [ownerPubkey, props]);\n\n  const confirmPay = useCallback(async () => {\n    if (!paySheet || payBusy) return;\n    setPayBusy(true);\n    try {\n      const ps = require('./proposal_share');\n      const getId = ps._kvResolveIdentity || ps.resolveKvIdentity || ps.kvResolveIdentity || ps.getKvIdentity || ps.resolveIdentity;\n      let ident: any = getId ? await getId() : null;\n      if (!ident || !ident.address || !ident.privkey) {\n        const SS = require('expo-secure-store');\n        ident = { address: await SS.getItemAsync('kaspa_address'), privkey: await ps._kvResolvePrivHex(), network };\n      }\n      if (!ident || !ident.address || !ident.privkey) throw new Error('wallet identity unavailable');\n      const { sendKaspaViaRest } = require('./kaspa_rest_tx');\n      const r: any = await sendKaspaViaRest({\n        senderAddress: ident.address,\n        recipientAddress: paySheet.addr,\n        amountSompi: BigInt(Math.round(paySheet.kas * 1e8)),\n        privateKeyHex: ident.privkey,\n        network: (ident.network || network) as any,\n      });\n      if (r && r.success && (r.txId || r.transactionId)) {\n        const txid = String(r.txId || r.transactionId);\n        setPayDone(txid);\n        webRef.current?.injectJavaScript('try{window.dispatchEvent(new CustomEvent(\"kvpay\",{detail:{ok:true,txid:\"' + txid + '\",kas:' + paySheet.kas + '}}))}catch(e){};true;');\n      } else {\n        setNotice('Payment failed: ' + String((r && r.error) || 'unknown'));\n        setPaySheet(null);\n      }\n    } catch (e: any) {\n      setNotice('Payment failed: ' + String(e?.message || e));\n      setPaySheet(null);\n    }\n    setPayBusy(false);\n  }, [paySheet, payBusy, network]);");
rep("pay-sheet-ui", "      {notice ? (", "      {paySheet ? (\n        <View style={{ position: 'absolute', left: 0, right: 0, top: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.78)', justifyContent: 'center', padding: 24 }}>\n          <View style={{ backgroundColor: '#17131f', borderColor: '#7c3aed', borderWidth: 2, borderRadius: 14, padding: 18 }}>\n            <Text style={{ color: '#b9a6ff', fontWeight: '900', fontSize: 16, letterSpacing: 2 }}>KV PAY</Text>\n            <Text style={{ color: '#fff', fontSize: 28, fontWeight: '800', marginTop: 8 }}>{paySheet.kas} KAS</Text>\n            {paySheet.memo ? <Text style={{ color: '#cbb9ff', fontSize: 13, marginTop: 2 }}>{paySheet.memo}</Text> : null}\n            <Text style={{ color: '#8a8098', fontSize: 11, marginTop: 12 }}>to</Text>\n            <Text style={{ color: '#e6e0f5', fontFamily: 'monospace', fontSize: 11 }} numberOfLines={2}>{paySheet.addr}</Text>\n            <Text style={{ color: '#f0c860', fontSize: 11, marginTop: 12 }}>\n              {'Requested by this ' + (props.game ? 'game' : 'page') + '. KAS only ever moves through this sheet - never type amounts, addresses or your seed inside a page.'}\n            </Text>\n            {payDone ? (\n              <Text style={{ color: '#34d399', fontSize: 12, marginTop: 12 }} numberOfLines={1}>{'sent \\u2713 ' + payDone.slice(0, 18) + '\\u2026'}</Text>\n            ) : null}\n            <View style={{ flexDirection: 'row', marginTop: 16 }}>\n              <TouchableOpacity disabled={payBusy} onPress={() => { setPaySheet(null); setPayDone(null); }}\n                style={{ flex: 1, padding: 12, alignItems: 'center' }}>\n                <Text style={{ color: '#aaa', fontWeight: '700' }}>{payDone ? 'CLOSE' : 'CANCEL'}</Text>\n              </TouchableOpacity>\n              {!payDone ? (\n                <TouchableOpacity disabled={payBusy} onPress={confirmPay}\n                  style={{ flex: 1, backgroundColor: payBusy ? '#555' : '#7c3aed', borderRadius: 10, padding: 12, alignItems: 'center', justifyContent: 'center' }}>\n                  <Text style={{ color: '#fff', fontWeight: '900' }}>{payBusy ? 'SENDING\\u2026' : 'CONFIRM & SEND'}</Text>\n                </TouchableOpacity>\n              ) : null}\n            </View>\n          </View>\n        </View>\n      ) : null}\n      {notice ? (");
fs.writeFileSync(P, CRLF ? s.replace(/\n/g, "\r\n") : s);
console.log("\npatched " + P + " (3 edits). kv://pay live for pages, dapps and games.");
