// wire_store_announce_tip.cjs - announce-only for stores, tips for stores+dapps.
//
// (1) ANNOUNCE-ONLY. Games had an announce button; stores and dapps did not.
//     So re-advertising a store whose registry entry had aged out meant a FULL
//     republish - every chunk paid for again (~77 KAS on a big one) to restate
//     something already on chain. Publish now stashes what announce needs, and
//     the new button re-stamps a fresh registry entry, with a freshly scanned
//     daa span, for the price of one announce (~1 KAS).
//
// (2) TIPS. tip_addr now rides the store and dapp coords, gated by the same
//     kv_tip_optin toggle as games - opt-in, absent entirely when off. The
//     storefront card grows a TIP button only when a store declares one.
//     Academics ride the store path, so they are covered by the same change.
//
// Requires wire_store_coords.cjs + fix_daa_window.cjs + wire_tip_optin.cjs.
// Run from layer1 root:  node src\\wire_store_announce_tip.cjs
const fs = require("fs");
function patch(P, edits, guard) {
  let s = fs.readFileSync(P, "utf8");
  const CRLF = s.includes("\r\n");
  if (CRLF) s = s.replace(/\r\n/g, "\n");
  if (s.includes(guard)) { console.log("already patched  [" + P + "]"); return; }
  for (const [name, a, b] of edits) {
    const f = s.split(a).length - 1;
    if (f !== 1) { console.error("ABORT [" + name + "]: found " + f + ", expected 1"); process.exit(1); }
    s = s.split(a).join(b); console.log("ok  [" + name + "]");
  }
  fs.writeFileSync(P, CRLF ? s.replace(/\n/g, "\r\n") : s);
}
patch("Workspace.tsx", [
  ["store-tip+stash", "            if (hi > 0) _stCoords = { pledge_kas: Math.round(pl / 1e7) / 10, daa_from: Math.max(0, Math.max(lo, hi - 14400) - 600), daa_to: hi + 600, ...(_stAnchor ? { anchor_hash: _stAnchor } : {}) };", "            let _tipOn = false;\n            try {\n              const AS = require('@react-native-async-storage/async-storage').default;\n              _tipOn = (await AS.getItem('kv_tip_optin')) === '1';\n            } catch {}\n            if (hi > 0) _stCoords = { pledge_kas: Math.round(pl / 1e7) / 10, daa_from: Math.max(0, Math.max(lo, hi - 14400) - 600), daa_to: hi + 600, ...(_stAnchor ? { anchor_hash: _stAnchor } : {}), ...(_tipOn && _addr ? { tip_addr: _addr } : {}) };\n            // Stash what ANNOUNCE-only needs, so re-advertising later costs ~1\n            // KAS instead of a full republish of every chunk.\n            try {\n              const AS = require('@react-native-async-storage/async-storage').default;\n              await AS.setItem('kv_store_pub_' + hostId, JSON.stringify({\n                storeAddress: _pub.storeAddress, cfgHash: _annHash, anchor: _stAnchor,\n                name: brandName, category: storeCategory, primaryLink,\n              }));\n            } catch {}"],
  ["dapp-tip", "                      if (hi > 0) _dpCoords = { pledge_kas: Math.round(pl / 1e7) / 10, daa_from: Math.max(0, Math.max(lo, hi - 14400) - 600), daa_to: hi + 600, ...(_dpAnchor ? { anchor_hash: _dpAnchor } : {}) };", "                      let _dpTip = false;\n                      try {\n                        const AS = require('@react-native-async-storage/async-storage').default;\n                        _dpTip = (await AS.getItem('kv_tip_optin')) === '1';\n                      } catch {}\n                      if (hi > 0) _dpCoords = { pledge_kas: Math.round(pl / 1e7) / 10, daa_from: Math.max(0, Math.max(lo, hi - 14400) - 600), daa_to: hi + 600, ...(_dpAnchor ? { anchor_hash: _dpAnchor } : {}), ...(_dpTip && _owner.address ? { tip_addr: _owner.address } : {}) };"],
  ["announce-handler", "  const handlePublishStorefront = async () => {", "  // ANNOUNCE-only for stores. Games had this; stores did not, so the only way\n  // to re-advertise a store whose announce had aged out was a full republish -\n  // every chunk again. This re-stamps a fresh registry entry from the stored\n  // publish details for the price of one announce (~1 KAS).\n  const handleAnnounceStore = async () => {\n    try {\n      setPubStage('Announcing to registry...');\n      const AS = require('@react-native-async-storage/async-storage').default;\n      const raw = await AS.getItem('kv_store_pub_' + hostId);\n      if (!raw) { Alert.alert('Nothing to announce', 'Publish this storefront once first - announce re-advertises an existing on-chain store.'); setPubStage(''); return; }\n      const st = JSON.parse(raw);\n      const { announceToRegistry } = require('./payload_publish');\n      const { _kvResolvePrivHex } = require('./proposal_share');\n      const _priv = await _kvResolvePrivHex();\n      const _addr2 = (await SecureStore.getItemAsync('kv_kaspa_address')) || (await SecureStore.getItemAsync('kaspa_address')) || '';\n      const _owner2 = { privateKeyHex: _priv, pubkeyHex: userPubkey, address: _addr2, network: 'testnet-10' as any };\n      let coords: any = undefined;\n      try {\n        let lo = Number.MAX_SAFE_INTEGER, hi = 0, pl = 0;\n        const ur = await fetch('https://api-tn10.kaspa.org/addresses/' + encodeURIComponent(st.storeAddress) + '/utxos');\n        for (const u of (await ur.json()) || []) {\n          const dd = Number(u.utxoEntry?.blockDaaScore || u.blockDaaScore || 0);\n          if (dd > 0) { if (dd < lo) lo = dd; if (dd > hi) hi = dd; }\n          pl += Number(u.utxoEntry?.amount || u.amount || 0);\n        }\n        const tipOn2 = (await AS.getItem('kv_tip_optin')) === '1';\n        if (hi > 0) coords = { pledge_kas: Math.round(pl / 1e7) / 10, daa_from: Math.max(0, Math.max(lo, hi - 14400) - 600), daa_to: hi + 600, ...(st.anchor ? { anchor_hash: st.anchor } : {}), ...(tipOn2 && _addr2 ? { tip_addr: _addr2 } : {}) };\n      } catch {}\n      const ann: any = await announceToRegistry(_owner2 as any, st.storeAddress, st.name, st.category, 'store', { primaryLink: st.primaryLink, configHash: st.cfgHash, coords });\n      setPubStage('');\n      if (ann && ann.success !== false) Alert.alert('Announced \\u2713', 'Re-advertised to the registry for ~1 KAS. Chunks untouched.');\n      else Alert.alert('Announce failed', String((ann && ann.error) || 'unknown'));\n    } catch (e: any) { setPubStage(''); Alert.alert('Announce failed', String(e?.message || e)); }\n  };\n\n  const handlePublishStorefront = async () => {"],
  ["announce-button", "          <TouchableOpacity style={{ flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: rs.s(6), backgroundColor: '#4f46e5', borderRadius: rs.s(10), paddingVertical: rs.s(10) }} onPress={handlePublishStorefront} disabled={isPublishing}>", "          <TouchableOpacity style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: rs.s(4), borderColor: '#7c5cff', borderWidth: 1, borderRadius: rs.s(10), paddingVertical: rs.s(10), paddingHorizontal: rs.s(10) }} onPress={handleAnnounceStore} disabled={isPublishing}>\n            <Text style={{ color: '#b9a6ff', fontWeight: 'bold', fontSize: rs.font(11) }}>Announce</Text>\n          </TouchableOpacity>\n          <TouchableOpacity style={{ flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: rs.s(6), backgroundColor: '#4f46e5', borderRadius: rs.s(10), paddingVertical: rs.s(10) }} onPress={handlePublishStorefront} disabled={isPublishing}>"],
], "handleAnnounceStore");
patch("VillageMailbox.tsx", [["store-tip-button", "function StorefrontCard({ item, onPress }: { item: StorefrontEntry; onPress: () => void }) {\n  return (\n    <TouchableOpacity style={cardStyles.storefrontCard} onPress={onPress} activeOpacity={0.8}>", "function StorefrontCard({ item, onPress }: { item: StorefrontEntry; onPress: () => void }) {\n  const tipAddr = (item as any)?.coords?.tip_addr;\n  const doTip = () => {\n    if (!tipAddr) return;\n    Alert.alert(\n      'Tip ' + (item.storeName || 'this store'),\n      'Send 1 KAS straight to the address this store declared in its announce?\\n\\n' + String(tipAddr)\n        + '\\n\\nNever send KAS to an address typed inside a page \\u2014 only through prompts like this.',\n      [\n        { text: 'Cancel', style: 'cancel' },\n        { text: 'Send 1 KAS', onPress: async () => {\n            try {\n              const ps = require('./proposal_share');\n              const SS = require('expo-secure-store');\n              const sender = await SS.getItemAsync('kaspa_address');\n              const priv = await ps._kvResolvePrivHex();\n              if (!sender || !priv) throw new Error('wallet identity unavailable');\n              const { sendKaspaViaRest } = require('./kaspa_rest_tx');\n              const r: any = await sendKaspaViaRest({\n                senderAddress: sender, recipientAddress: String(tipAddr),\n                amountSompi: 100000000n, privateKeyHex: priv, network: 'testnet-10' as any,\n              });\n              if (r && r.success) Alert.alert('Tip sent \\u2713');\n              else Alert.alert('Tip failed', String((r && r.error) || 'unknown'));\n            } catch (e: any) { Alert.alert('Tip failed', String(e?.message || e)); }\n          } },\n      ],\n    );\n  };\n  return (\n    <TouchableOpacity style={cardStyles.storefrontCard} onPress={onPress} activeOpacity={0.8}>\n      {tipAddr ? (\n        <TouchableOpacity onPress={doTip}\n          style={{ position: 'absolute', right: 6, bottom: 6, zIndex: 20, borderColor: '#7c3aed', borderWidth: 1, borderRadius: 6, paddingHorizontal: 6, paddingVertical: 2 }}>\n          <Text style={{ color: '#b9a6ff', fontSize: 10, fontWeight: '700' }}>{'\\U0001F49C TIP'}</Text>\n        </TouchableOpacity>\n      ) : null}"]], "tipAddr");
console.log("\ndone. Stores announce for ~1 KAS; stores, dapps and academics can take tips.");
