// wire_card_tip.cjs - TIP THE DEV on the Games card (dev opt-in via tip_addr).
//
// Button renders ONLY when the announce's quad declares tip_addr. Flow: amount
// prompt -> full-address confirm (with the never-type-addresses-in-pages
// rule) -> user-signed send. KasVillage never holds or routes the funds.
// Requires wire_card_trust.cjs + wire_card_bayes.cjs applied.
// Run from layer1 root:  node src\\wire_card_tip.cjs
const fs = require("fs");
const P = "VillageMailbox.tsx";
let s = fs.readFileSync(P, "utf8");
const CRLF = s.includes("\r\n");
if (CRLF) s = s.replace(/\r\n/g, "\n");
if (s.includes("TIP THE DEV")) { console.log("already patched"); process.exit(0); }
function rep(name, a, b) {
  const f = s.split(a).length - 1;
  if (f !== 1) { console.error("ABORT [" + name + "]: found " + f + ", expected 1"); process.exit(1); }
  s = s.split(a).join(b); console.log("ok  [" + name + "]");
}
rep("tip-handler", "  const installGame = async (item: any) => {", "  const tipDev = (item: any) => {\n    const addr = item && item.quad && item.quad.tip_addr;\n    if (!addr || !(String(addr).startsWith('kaspatest:') || String(addr).startsWith('kaspa:'))) return;\n    // App-native tip: same identity + send rail as KV PAY; two-step confirm\n    // with the full recipient shown. KasVillage never touches the funds.\n    Alert.prompt(\n      'Tip ' + (item.name || 'the dev'),\n      'KAS amount \\u2014 goes directly to the address this dev declared in their announce.',\n      [\n        { text: 'Cancel', style: 'cancel' },\n        { text: 'Next', onPress: (val?: string) => {\n            const kas = Number(val || '0');\n            if (!(kas > 0) || kas > 5000) { Alert.alert('Invalid amount'); return; }\n            Alert.alert(\n              'Confirm tip: ' + kas + ' KAS',\n              'To (declared by dev):\\n' + addr + '\\n\\nNever send KAS to addresses typed inside a game or page \\u2014 only through prompts like this.',\n              [\n                { text: 'Cancel', style: 'cancel' },\n                { text: 'CONFIRM & SEND', onPress: async () => {\n                    try {\n                      const ps = require('./proposal_share');\n                      const SS = require('expo-secure-store');\n                      const sender = await SS.getItemAsync('kaspa_address');\n                      const priv = await ps._kvResolvePrivHex();\n                      if (!sender || !priv) throw new Error('wallet identity unavailable');\n                      const { sendKaspaViaRest } = require('./kaspa_rest_tx');\n                      const r: any = await sendKaspaViaRest({\n                        senderAddress: sender, recipientAddress: String(addr),\n                        amountSompi: BigInt(Math.round(kas * 1e8)),\n                        privateKeyHex: priv, network: 'testnet-10' as any,\n                      });\n                      if (r && r.success && (r.txId || r.transactionId)) Alert.alert('Tip sent \\u2713', String(r.txId || r.transactionId).slice(0, 20) + '\\u2026');\n                      else Alert.alert('Tip failed', String((r && r.error) || 'unknown'));\n                    } catch (e: any) { Alert.alert('Tip failed', String(e?.message || e)); }\n                  } },\n              ],\n            );\n          } },\n      ],\n      'plain-text', '', 'decimal-pad',\n    );\n  };\n\n  const installGame = async (item: any) => {");
rep("tip-button", "      <TouchableOpacity onPress={() => onInstall(item)} disabled={!!installing}\n        style={{ marginTop: 8, backgroundColor: installing ? '#999' : (item.warn ? '#b91c1c' : '#7c3aed'), borderRadius: 8, paddingVertical: 6, alignItems: 'center' }}>\n        <Text style={{ color: '#fff', fontWeight: '700', fontSize: 12 }}>{installing ? 'DOWNLOADING\u2026' : 'DOWNLOAD'}</Text>\n      </TouchableOpacity>", "      <TouchableOpacity onPress={() => onInstall(item)} disabled={!!installing}\n        style={{ marginTop: 8, backgroundColor: installing ? '#999' : (item.warn ? '#b91c1c' : '#7c3aed'), borderRadius: 8, paddingVertical: 6, alignItems: 'center' }}>\n        <Text style={{ color: '#fff', fontWeight: '700', fontSize: 12 }}>{installing ? 'DOWNLOADING\u2026' : 'DOWNLOAD'}</Text>\n      </TouchableOpacity>\n      {item.quad && item.quad.tip_addr && onTip ? (\n        <TouchableOpacity onPress={() => onTip(item)}\n          style={{ marginTop: 6, borderColor: '#7c3aed', borderWidth: 1, borderRadius: 8, paddingVertical: 5, alignItems: 'center' }}>\n          <Text style={{ color: '#b9a6ff', fontWeight: '700', fontSize: 12 }}>{'\ud83d\udc9c TIP THE DEV'}</Text>\n        </TouchableOpacity>\n      ) : null}");
rep("card-sig", "function GameRegistryCard({ item, onInstall, installing }: any) {", "function GameRegistryCard({ item, onInstall, installing, onTip }: any) {");
rep("card-render", "      case 'games': return <GameRegistryCard item={item} onInstall={installGame} installing={installingGame === (item.quad && item.quad.head)} />;", "      case 'games': return <GameRegistryCard item={item} onInstall={installGame} installing={installingGame === (item.quad && item.quad.head)} onTip={tipDev} />;");
fs.writeFileSync(P, CRLF ? s.replace(/\n/g, "\r\n") : s);
console.log("\npatched " + P + " (4 edits). TIP THE DEV live on opted-in game cards.");
