// wire_workspace_publish_v2.cjs — UNIVERSAL chain-game publisher in Workspace.
//
// Run from the layer1 root (CRLF-safe):  node src\wire_workspace_publish_v2.cjs
//
// Replaces the KasCity-only KvChainGamePublish (if v1 was applied) or inserts
// fresh. The panel now lists EVERY game in games_to_publish.js (generated by
// make_chain.cjs), one PUBLISH row per game:
//   - HEAD must equal TRUSTED_GAMES[gameId]   (the pin gate — unverified
//     games refuse to publish even for the owner)
//   - slot addresses deriveStoreKeys(priv, nonceBase+slot), manifest at
//     nonceBase+86  (KasCity keeps 9414 -> manifest 9500, same as before)
//   - publishGamePuzzle -> round-trip fetchGamePuzzle -> launch triple copied.
// Owner gate unchanged: only KV_PUBLISHER_ADDR sees the panel.
const fs = require("fs");
const P = "Workspace.tsx";
let s = fs.readFileSync(P, "utf8");
const CRLF = s.includes("\r\n");
if (CRLF) s = s.replace(/\r\n/g, "\n");
const HAVE_V2 = s.includes("KV-CHAIN-GAME v2");
let n = 0;
function rep(name, anchor, to, expected) {
  const found = s.split(anchor).length - 1;
  if (found !== expected) { console.error(`ABORT [${name}]: expected ${expected}, found ${found}`); process.exit(1); }
  s = s.split(anchor).join(to); n++; console.log("ok  [" + name + "]");
}

const COMPONENT = `
// ============================================================================
// [KV-CHAIN-GAME v2] owner-gated UNIVERSAL publisher: any pinned chain game
// ============================================================================
const KV_PUBLISHER_ADDR = 'kaspatest:qp7592kfylul443ee5950xe7jgv4rkgrv87ju8s96xz0sy3t79cnxmdmtcusz';
const KvChainGamePublish: React.FC = () => {
  const [myAddr, setMyAddr] = useState('');
  const [glog, setGlog] = useState<string[]>([]);
  const [gbusy, setGbusy] = useState('');
  const [triple, setTriple] = useState('');
  useEffect(() => { (async () => {
    setMyAddr((await SecureStore.getItemAsync('kv_kaspa_address')) || (await SecureStore.getItemAsync('kaspa_address')) || '');
  })(); }, []);
  const gadd = (l: string) => setGlog((p) => [...p.slice(-150), l]);
  const GAMES: Record<string, { bundle: any; head: string; nonceBase: number }> = require('./games_to_publish.js');
  const runPublish = async (gameId: string) => {
    if (gbusy) return;
    setGbusy(gameId); setGlog([]); setTriple('');
    try {
      const entry = GAMES[gameId];
      const { publishGamePuzzle, fetchGamePuzzle, TRUSTED_GAMES } = require('./game_chunks');
      const { deriveStoreKeys } = require('./payload_publish');
      const { _kvResolvePrivHex } = require('./proposal_share');
      if (TRUSTED_GAMES[gameId] !== entry.head || entry.bundle.manifest.head !== entry.head) {
        gadd('ERROR: ' + gameId + ' HEAD is not pinned in TRUSTED_GAMES — verify with TownHall first'); setGbusy(''); return;
      }
      const priv = await _kvResolvePrivHex();
      if (!priv || !myAddr) { gadd('ERROR: wallet keys unavailable'); setGbusy(''); return; }
      const pub = bytesToHex(secp256k1.getPublicKey(hexToBytes(priv), true));
      const owner = { privateKeyHex: priv, pubkeyHex: pub, address: myAddr, network: 'testnet-10' as any };
      const m = entry.bundle.manifest;
      const slots = Math.max(...m.frags.map((f: any) => f.slot)) + 1;
      const slotAddresses = Array.from({ length: slots }, (_, i) => deriveStoreKeys(priv, entry.nonceBase + i, owner.network).address);
      const manifestAddress = deriveStoreKeys(priv, entry.nonceBase + 86, owner.network).address;
      slotAddresses.forEach((a: string, i: number) => gadd('slot ' + i + ' ' + a));
      gadd('manifest ' + manifestAddress);
      gadd(entry.bundle.frags.length + ' fragments -> publishing (keep this screen open)…');
      const t0 = Date.now();
      const res = await publishGamePuzzle(owner, m, entry.bundle.frags, slotAddresses, manifestAddress,
        (done: number, total: number) => gadd('fragment ' + done + '/' + total + ' (' + Math.round((Date.now() - t0) / 1000) + 's)'));
      if (!res.success) { gadd('PUBLISH FAILED: ' + res.error); setGbusy(''); return; }
      gadd('manifest published, hash ' + res.manifestHash);
      gadd('verifying: solving the puzzle back from chain…');
      const back = await fetchGamePuzzle(manifestAddress, res.manifestHash, m.head, owner.network);
      gadd(back.html ? 'ROUND-TRIP OK (' + back.html.length + ' bytes)' : 'ROUND-TRIP FAILED: ' + back.error);
      const t = JSON.stringify({ game: gameId, manifestAddress, manifestHash: res.manifestHash, head: m.head });
      setTriple(t);
      await Clipboard.setStringAsync(t);
      gadd('LAUNCH TRIPLE copied to clipboard.');
    } catch (e: any) {
      gadd('ERROR: ' + String(e?.message || e));
    } finally { setGbusy(''); }
  };
  if (myAddr !== KV_PUBLISHER_ADDR) return null;   // owner gate
  return (
    <View style={{ backgroundColor: '#141210', borderRadius: 12, padding: 14, marginBottom: 16, borderWidth: 1, borderColor: '#6a5a34' }}>
      <Text style={{ color: '#f0c860', fontWeight: '900', fontFamily: 'monospace', fontSize: 14 }}>?? PUBLISH CHAIN GAMES</Text>
      <Text style={{ color: '#9a8f78', fontFamily: 'monospace', fontSize: 10, marginVertical: 6 }}>owner-only · pinned HEADs only · sequential txs</Text>
      {Object.entries(GAMES).map(([id, e]: any) => (
        <TouchableOpacity key={id} disabled={!!gbusy} onPress={() => runPublish(id)}
          style={{ backgroundColor: '#2a2118', borderWidth: 1, borderColor: '#6a5a34', borderRadius: 8, padding: 10, alignItems: 'center', marginBottom: 6, opacity: gbusy && gbusy !== id ? 0.4 : 1 }}>
          <Text style={{ color: '#f0c860', fontFamily: 'monospace', fontWeight: '700', fontSize: 12 }}>
            {gbusy === id ? 'PUBLISHING ' + id + '…' : 'PUBLISH ' + id + ' (' + e.bundle.frags.length + ' frags)'}
          </Text>
        </TouchableOpacity>
      ))}
      <View style={{ maxHeight: 220, marginTop: 4 }}>
        <ScrollView nestedScrollEnabled>
          {glog.map((l, i) => <Text key={i} style={{ color: '#e8ddc8', fontSize: 10, fontFamily: 'monospace' }}>{l}</Text>)}
        </ScrollView>
      </View>
      {triple ? <Text selectable style={{ color: '#3fc1b0', fontSize: 10, fontFamily: 'monospace', marginTop: 6 }}>{triple}</Text> : null}
    </View>
  );
};
`;

const V1_START = "// ============================================================================\n// [KV-CHAIN-GAME] owner-gated publisher: KasCity puzzle -> Kaspa payload rail";
if (HAVE_V2) {
  console.log("component already v2");
} else if (s.includes(V1_START)) {
  const a = s.indexOf(V1_START);
  const endMark = "};\n";
  const compEnd = s.indexOf("\n// DAPP QUALITY GATE MODAL", a);
  if (compEnd < 0) { console.error("ABORT: cannot find end of v1 component"); process.exit(1); }
  s = s.slice(0, a) + COMPONENT.trim() + "\n" + s.slice(compEnd + 1); n++;
  console.log("ok  [replace-v1-component]");
} else {
  rep("component", "// DAPP QUALITY GATE MODAL", COMPONENT + "\n// DAPP QUALITY GATE MODAL", 1);
  rep("mount",
    "        {activeView === 'dapps' && (\n          <SectionCard title=\"DApp & Game Management\">",
    "        {activeView === 'dapps' && (\n          <SectionCard title=\"DApp & Game Management\">\n            <KvChainGamePublish />", 1);
}

// relocate the mount if a previous run put it under Academic > submit
const OLD_MOUNT = "            {activeTab === 'submit' && (\n              <View style={acStyles.tabContent}>\n                <KvChainGamePublish />";
if (s.includes(OLD_MOUNT)) {
  s = s.split(OLD_MOUNT).join("            {activeTab === 'submit' && (\n              <View style={acStyles.tabContent}>");
  console.log("ok  [unmount-academic]"); n++;
}
const DAPPS_MOUNT = "        {activeView === 'dapps' && (\n          <SectionCard title=\"DApp & Game Management\">";
if (!s.includes(DAPPS_MOUNT + "\n            <KvChainGamePublish />")) {
  if (s.split(DAPPS_MOUNT).length - 1 !== 1) { console.error("ABORT [mount-dapps]: anchor not found"); process.exit(1); }
  s = s.split(DAPPS_MOUNT).join(DAPPS_MOUNT + "\n            <KvChainGamePublish />");
  console.log("ok  [mount-dapps]"); n++;
}
fs.writeFileSync(P, CRLF ? s.replace(/\n/g, "\r\n") : s);
console.log("\npatched " + P + " (" + n + " patches).");
console.log("prereq: node src\\make_chain.cjs <input.html> <gameId> [--kascity-music]");
console.log("restart Metro with --clear so the registry + bundles get picked up");
